### ISSUE TITLE
Update lock?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#103]
I have noticed some devices getting stuck whilst trying to update due to an update lock being applied in `/tmp/balena/updates.lock`

On occasion I have seen devices stuck in this state for at least a few hours. The only way to seemingly fix it is a forced reboot.

However, what is not clear, is where the lockfile is coming from? As I can't see any code in our codebase that would be applying one. So presumably it is something to do with the balena supervisor?

Ref: https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/

<img width="1212" alt="Screenshot 2021-08-04 at 00 33 58" src="https://user-images.githubusercontent.com/3359418/128099478-066827a9-98dc-4c15-8294-589f21fc173c.png">

**Comment by vpetersson** [comment]
Don't find any matches on this in our code base either. It's most likely it was either created by hand (by someone with Balena access) or by Balena's supervisor.

**Comment by shawaj** [comment]
must be by the supervisor, the question is - why?

**Comment by vpetersson** [comment]
I don't see why the supervisor. I would suspect fat fingers as I was able to find it in the drop-down.

**Comment by shawaj** [comment]
What do you mean the drop-down? I don't see an update lock in the drop-down actions list on the device?

**Comment by vpetersson** [comment]
<img width="454" alt="Screen Shot 2021-08-11 at 8 43 55 AM" src="https://user-images.githubusercontent.com/357664/128989993-1f963acc-6206-45d9-ab1b-45f807aa2b6a.png">

**Comment by shawaj** [comment]
Pin to release doesn't introduce an update lock file as far as I am aware - it just tells the supervisor to pin the device to a specific release. 

"Pin to release" was not set on this device...but it did have an update.lock file

That is what is so strange...

**Comment by suprnrdy** [comment]
Does this update lock also show up on the diagnostic side as "Miner is still loading..." issue?

**Comment by vpetersson** [comment]
@suprnrdy No, i don't think that's related. "Miner is loading..." just means that the local diagnostics tool hasn't been able to load data from the miner software as it hasn't started yet properly.

**Comment by shawaj** [comment]
@suprnrdy yeah and that can be due to a variety of issues - but essentially all it means is that the helium miner container hasn't fully loaded or is unresponsive. it is not a particularly useful error message as it can relate to a variety of problems

**Comment by KevinWassermann94** [comment]
@shawaj @vpetersson I have been in contact with the Balena team about this. The update locks are applied by the supervisor, usually when it is updating. The update lock should be deleted after the supervisor has finished, but most likely due to it crashing the update locks won't be deleted. They are currently investigating into the issue

**Comment by shawaj** [comment]
@KevinWassermann94 awesome thanks for reaching out to them. Good to know that I wasn't imagining it 🤣

**Comment by shawaj** [comment]
I guess we can handle this stuff with hm-watchdog at least partially

**Comment by vpetersson** [comment]
@shawaj this seems to be inside the container, and not on the shared file system. As such, the watchdog wouldn't be able to find that. 

That said, we could add a simple check (eg if the file is older than 24h) to the init script and just automatically delete it.

**Comment by shawaj** [comment]
@vpetersson Watchdog would have host filesystem access.... So it could access the volumes of other containers

**Comment by vpetersson** [comment]
Hmm, no it would just be another container. We would have Supervisor API access to interface with other containers, but that wouldn't give us host file system access. We could potentially volume map that but I don't know how I feel about that.

**Comment by shawaj** [comment]
Have temporarily overridden the update lock on all fleets. Balena have said it shouldn't cause any issues

**Comment by shawaj** [comment]
closing this in favour of #266 which is the over-arching issue for all update issues.

also, as we currently do not use update locks for anything in our application, we have set all fleets in our balena account to automatically override the supervisor update lock for now.

we can always revisit this in the future if we need to use the update lock at all
