### ISSUE TITLE
Doesn't checks for IP change

### ISSUE THREAD

**Issue by dakky221** [NebraLtd/helium-miner-software#108]
On dynamic IP connections, where public external IP likes to change multiple times per day, the miner doesn't checks for the real external IP.

That leads to the wrong IP being reported to the blockchain and eventually relayed connection. Rebooting the miner is a workaround as it then updates the chain with the new current IP and is no longer relayed.

Simple workaround is to add periodic check for external public IP and update the chain when necessary. Something like dynamic dns updaters do.

**Comment by dakky221** [comment]
So let me just add more comments on this... so with helium hiker bot, it is possible to see the listen_addr written in blockchain... it says something like

+----------------------------+
| listen_addrs (prioritized) |
+----------------------------+
|/ip4/93.137.187.46/tcp/44158|
+----------------------------+

After the public ip changes, that record stays unchanged till the reboot of the miner itself. Then it updates the record and beacons start coming through.

**Comment by shawaj** [comment]
You would need to report that at https://github.com/helium/miner instead as it is helium libp2p in the miner code that deals with reporting the IP address to the blockchain

**Comment by dakky221** [comment]
I figured out it has to do with Nebra because Sensecap determines the correct public ip on its own and Nebra determines it only after a reboot/power cycle.

**Comment by shawaj** [comment]
I find it hard to believe that is the case. Probably you just need to leave it longer for libp2p to pick up the new IP address.

Almost every provider these days uses a dynamic IP address unless you specifically pay extra for static IP. If this was really an issue I would expect it to have been reported many many times before.

Having said that, if you have can send an email ticket to us with the details listed here https://helium.nebra.com/support?id=email

And reply back with your ticket number, then we can take a look at your specific unit.

Please also link to this issue in the email so we can know they are related.

**Comment by shawaj** [comment]
@dakky221 forgot to tag you

**Comment by anthonyra** [comment]
Interesting @dakky221 do you know if Sensecap runs the miner in a Docker container? I "believe" Nebra does and so does Bobcat and they both have issues with updating the dynamic IP address...

**Comment by dakky221** [comment]
I have no idea. I solved it by putting Nebra on a smart plug, it reboots it every time the IP changes. Works so far.

**Comment by karlbnapf** [comment]
I have the same problem with a RAK hotspot. Wouldn't it generally be an option to let users specify a DynDNS name?

**Comment by dakky221** [comment]
Yeah, it would help, but as Shawaj said it's not Nebra's issue but Helium so it should be asked there. not here.

**Comment by MagNaMan** [comment]
If anyone wants a simple app to track and text or email yourself.
https://www.gearboxcomputers.com/products/ip-watcher/

**Comment by anthonyra** [comment]
> I have the same problem with a RAK hotspot. Wouldn't it generally be an option to let users specify a DynDNS name?

Are you sure it's the same issue? I've seen issues with RAK staying sync which would be different than having the wrong or no listen_addrs.. because your miner does outbound request for blocks to sync. If you have a screwed up listen_addrs all out bound are unaffected (challenge creations, witnesses, and data credits) the only inbound is beacons.

**Comment by shawaj** [comment]
Related to https://github.com/helium/miner/issues/998 and https://github.com/helium/miner/issues/916

**Comment by shawaj** [comment]
Closed by https://github.com/helium/erlang-libp2p/pull/379
