### ISSUE TITLE
Not Connected To Helium Network, Not Connected To Blockchain

### ISSUE THREAD

**Issue by causticphoton** [NebraLtd/helium-miner-software#113]
Main-Vinyl-Jellyfish came online and synced, made some rewards, then suddenly went offline from Aug 9 until now.
Local Diagnostics says _Miner Connected To Blockchain	False_.
Remote Dashboard says _Connected To Helium Network:	No_.
I removed the Wi-Fi and Bluetooth USB adapters and connected the hotspot via Ethernet cable only.
Port forwarding setup on the host router/firewall and I confirmed it is working.
Dashboard sync percentage keeps dropping.
Installed indoors at 22C.
Removed the lid to prevent overheating of CPU on Aug 12.
Filed support ticket #264836 and #265387 with no response from Nebra support.

**Local Diagnostics**:
Sync Percentage	0.0%
Height Status	0 / 970400
Firmware Version	2021.08.16.1
Frequency	915
Region Plan	US915
Variant	Nebra Indoor Hotspot Gen 1
Miner Connected To Blockchain	False
Miner Relayed	False
ECC Detected	True
ETH0 MAC	xx:xx:xx:xx:4C:66
WLAN0 MAC	None
Raspberry Pi Serial	00000000f57bxxxx
Bluetooth Detected	False
LoRa Operational	True
Modem Detected	False

**Remote Dashboard**:
Connected To Helium Network:	No
Blockchain Sync Status:	98.73%

Connected To Update Server: Yes
Model: Nebra Indoor Hotspot Gen 1
IP Address: 192.168.1.100
CPU Usage: ~86%
CPU Temperature: ~62C
Memory Usage: 356 / 962 MB
Storage Usage: 5.7 / 27.8 GB

**Comment by shawaj** [comment]
Your device is offline currently but from the logs appears to be suffering from this issue https://github.com/helium/miner/issues/978

Unfortunately we need to wait for a fix from helium for this issue.

We can attempt a fix once the unit is back online. But this is the wrong place for this support so please keep it on the support ticket instead

**Comment by causticphoton** [comment]
I have obtained the unit back from my host. It's now "online" but still refuses to connect to the blockchain.
Is there a "factory reset" we can do, or a serial debug console that would allow me to see some logs, or properly diagnose?

**Comment by Spiridon9** [comment]
Hey there, 

i have the same issue like "causticphoton" ^^
My indoor Nebra hot spot EU868 - Joyous Ceramic Stallion is syncing for 9 days since 12.08.21

Sync Percentage	0.00%
Height Status	0 / 975442
Firmware Version	2021.08.16.1
Frequency	868
Region Plan	EU868
Variant	Nebra Indoor Hotspot Gen 1
Miner Connected To Blockchain	False

Miner Relayed	False
ECC Detected	True
ETH0 MAC	xx:xx:xx:xx:C9:F7
WLAN0 MAC	xx:xx:xx:xx:7D:B1
Raspberry Pi Serial	00000000ff52xxxx
Bluetooth Detected	True
LoRa Operational	True

Can you help please

**Comment by shawaj** [comment]
@Spiridon9 @causticphoton please reply on the support tickets

**Comment by Spiridon9** [comment]
ticket ID #267178 - I hope we do not need to wait forever
