### ISSUE TITLE
Not working HS - ticket nr. 258202

### ISSUE THREAD

**Issue by Laconesmrtelny** [NebraLtd/helium-miner-software#115]
Hello guys,
because your support via mail is too slow i am asking you for help here.
Please check ticket 258202
First launch of HS was OK but after few hours it went offline and since that time it is not working, maybe it could be online for some time because i have tried to restart HS many times, but now it seems dead at all. Also green LED turn off.
you asked for many pics of components inside and also for video how LEDs inside working, but no response since that time.
here is link for video:
https://drive.google.com/file/d/1bVVRS_oLp1cDvDRlMD-P8M6MHNxxLa3l/view?usp=sharing

we are solving this issue almost month and i am tired with that...so if this has no solution, please give me the contact person for claim.

thank you

**Comment by shawaj** [comment]
If you have a ticket open this will be dealt with directly via the ticket.
