### ISSUE TITLE
Miner Connected To Blockchain False

### ISSUE THREAD

**Issue by Spiridon9** [NebraLtd/helium-miner-software#119]
Hey there,

I am not sure if this is the right place to ask for help.
i have this issue - Miner Connected To Blockchain False
My indoor Nebra hot spot EU868 - Joyous Ceramic Stallion is syncing for 9 days since 12.08.21

Sync Percentage 0.00%
Height Status 0 / 975442
Firmware Version 2021.08.16.1
Frequency 868
Region Plan EU868
Variant Nebra Indoor Hotspot Gen 1
Miner Connected To Blockchain False

Miner Relayed False
ECC Detected True
ETH0 MAC xx:xx:xx:xx:C9:F7
WLAN0 MAC xx:xx:xx:xx:7D:B1
Raspberry Pi Serial 00000000ff52xxxx
Bluetooth Detected True
LoRa Operational True

Can you help please

**Comment by vpetersson** [comment]
Please contact support@nebra.com.

**Comment by shawaj** [comment]
Yes send an email and include following

- Model of unit?
- Mac address of the unit (Shown as ETH on sticker)?
- Frequency of the unit (Shown as Freq on sticker)?
- How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular)?
- How are you powering the unit? (included adaptor, PoE, third party adaptor)

If the issue relates to initial setup of the hotspot, please also include:

- What make & model of phone are you using?
- What version of the Helium App are you using?
-Do you have any screenshots of any error codes?

**Comment by Spiridon9** [comment]
Model of unit? - Nebra Indoor 868

Mac address of the unit (Shown as ETH on sticker)? - ETH: F0:4C:D5:03:C9:F7 

Frequency of the unit (Shown as Freq on sticker)? - FREQ: 868

How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular)? - Wi-Fi ( I also tried Ethernet - same issue )

How are you powering the unit? (included adaptor, PoE, third party adaptor) - included adaptor

If the issue relates to initial setup of the hotspot, please also include:

What make & model of phone are you using? - Samsung Galaxy Edge7

What version of the Helium App are you using? - v3.4.7

-Do you have any screenshots of any error codes? - attached screenshots of Helium App diagnostic and IP diagnostic

-- 
Mit freundlichem Gruß 

Mancho Manchev
Visual Artist

https://www.shutterstock.com/video/gallery/video-lord-1177148/

https://www.youtube.com/c/moremotionvisuals

Seilerstr. 23 A
60313 Frankfurt

Mob: 0157 57480565
E-Mail: ***@***.***
     Am Samstag, 21. August 2021, 15:02:57 MESZ hat Aaron Shaw ***@***.***> Folgendes geschrieben:  
 
 


Yes send an email and include following
   
   - Model of unit?
   - Mac address of the unit (Shown as ETH on sticker)?
   - Frequency of the unit (Shown as Freq on sticker)?
   - How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular)?
   - How are you powering the unit? (included adaptor, PoE, third party adaptor)

If the issue relates to initial setup of the hotspot, please also include:
   
   - What make & model of phone are you using?
   - What version of the Helium App are you using?   
-Do you have any screenshots of any error codes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shawaj** [comment]
@Spiridon9 please send via email

**Comment by Spiridon9** [comment]
Oh sorry,

thank you for editing the ETH

**Comment by Spiridon9** [comment]
Nebra App Screenshot update 

-- 
Mit freundlichem Gruß 

Mancho Manchev
Visual Artist

https://www.shutterstock.com/video/gallery/video-lord-1177148/

https://www.youtube.com/c/moremotionvisuals

Seilerstr. 23 A
60313 Frankfurt

Mob: 0157 57480565
E-Mail: ***@***.***
     Am Samstag, 21. August 2021, 16:07:57 MESZ hat Mancho Manchev ***@***.***> Folgendes geschrieben:  
 
  

Model of unit? - Nebra Indoor 868

Mac address of the unit (Shown as ETH on sticker)? - ETH: F0:4C:D5:03:C9:F7 

Frequency of the unit (Shown as Freq on sticker)? - FREQ: 868

How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular)? - Wi-Fi ( I also tried Ethernet - same issue )

How are you powering the unit? (included adaptor, PoE, third party adaptor) - included adaptor

If the issue relates to initial setup of the hotspot, please also include:

What make & model of phone are you using? - Samsung Galaxy Edge7

What version of the Helium App are you using? - v3.4.7

-Do you have any screenshots of any error codes? - attached screenshots of Helium App diagnostic and IP diagnostic

-- 
Mit freundlichem Gruß 

Mancho Manchev
Visual Artist

https://www.shutterstock.com/video/gallery/video-lord-1177148/

https://www.youtube.com/c/moremotionvisuals

Seilerstr. 23 A
60313 Frankfurt

Mob: 0157 57480565
E-Mail: ***@***.***
     Am Samstag, 21. August 2021, 15:02:57 MESZ hat Aaron Shaw ***@***.***> Folgendes geschrieben:  
 
 


Yes send an email and include following
   
   - Model of unit?
   - Mac address of the unit (Shown as ETH on sticker)?
   - Frequency of the unit (Shown as Freq on sticker)?
   - How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular)?
   - How are you powering the unit? (included adaptor, PoE, third party adaptor)

If the issue relates to initial setup of the hotspot, please also include:
   
   - What make & model of phone are you using?
   - What version of the Helium App are you using?   
-Do you have any screenshots of any error codes?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
