### ISSUE TITLE
Connected to server yes | Connected to helium network no

### ISSUE THREAD

**Issue by lvivlion** [NebraLtd/helium-miner-software#123]
Port is open, was working fine for 2 days

mac: **removed for security**

Hotspot Status
Connected To Update Server:
Yes
Model: Nebra Indoor Hotspot Gen 1

Connected To Helium Network: | No
-- | --
Blockchain Sync Status: | 99.72%

Was working ok for a day or two than got stuck, not working for over 3 days. tried rebooting, restarting, reconnecting to wifi even ethernet

**Comment by lvivlion** [comment]
@shawaj please take a look thank you. Tried rebooting still nothing

**Comment by lvivlion** [comment]
ticket ID #267556.

**Comment by shawaj** [comment]
Since you have a ticket already, closing this as that's the correct place for support of this nature.
