### ISSUE TITLE
Ethernet should take priority over wifi (wifi module on when connected via ethernet) causing issues?

### ISSUE THREAD

**Issue by lvivlion** [NebraLtd/helium-miner-software#131]
The latest update broke hotspot. Support suggested that weak wifi could be dropping. I connected now via ethernet. Hotspot shows 2 ips. 
https://dashboard.nebra.com/devices/000000002dee0988/

Connected To Update Server: Yes
Model: Nebra Indoor Hotspot Gen 1
IP Address: 10.0.0.24 (ethernet cable ) 10.0.0.244 (wifi)

267556 nebra ticket

Dashboard is not updating, says online tho

CPU Usage:
~100%
CPU Temperature:
~56C
Memory Usage:
353 / 962 MB
Storage Usage:
0.8 / 27.8 GB

**Comment by vpetersson** [comment]
Please contact support@nebra.com

**Comment by shawaj** [comment]
This possibly relates to #57
