### ISSUE TITLE
allow manual storage wipe

### ISSUE THREAD

**Issue by atartareanu** [NebraLtd/helium-miner-software#153]
By now we are aware of the auto-wipe function which is triggered when the storage will reach around 21GB, the estimate time between each auto-wipe is around 40 to 60 days.
When this happens the miner will start to sync from latest snapshot that has been released in the Helium GA update.
With the increase of the network in the past months, the time to catch-up with the blockchain (re-sync) is longer and longer, not to mention that Nebra does not have the greatest hardware.

Ideally the auto-wipe should happen shortly after a new released Helium GA update so that the sync time will be minimal, however this is purely random and for some unlucky people the re-sync can take one week if the latest GA is older than 14 days.

Can you please add a function in the dashboard or internal diagnostics page to allow users to do the auto-wipe by themselves ? or even better trigger the auto-wipe after each new GA release ?

we also heard that other vendors have the possibility to trigger a "fast sync" function through their dashboard, can Nebra add that too ?

Thank you

**Comment by vpetersson** [comment]
@atartareanu We're working on ways to improve the sync time instead. Hoping to ship something in the coming weeks.

**Comment by atartareanu** [comment]
I hope that _Hoping to ship something in the coming weeks_  will not turn into months. 
At least you can improve the product if we waited for so long and we are still suffering.

**Comment by shawaj** [comment]
See our latest update on Discord also https://discord.com/channels/404106811252408320/862486889578889256/893187186860625940

![Screenshot_20210930-192003_Discord](https://user-images.githubusercontent.com/3359418/135658464-e3fccb2c-b720-46df-8970-8af009be2d9f.jpg)

**Comment by atartareanu** [comment]
Yes, I saw that @shawaj , thank you for following this ticket and for the progress on the "instant sync", do you have any estimation for the launch date? is it a matter of days or weeks ?

**Comment by shawaj** [comment]
@atartareanu just pushed the instant sync now :-) 

https://discord.com/channels/404106811252408320/862486889578889256/893607778747285584

**Comment by atartareanu** [comment]
Oh wow, that's awesome ! thank you.

**Comment by shawaj** [comment]
> Oh wow, that's awesome ! thank you.

No problem at all! Have a great weekend.
