### ISSUE TITLE
fleet variables and configuration - automatic?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#164]
we currently use fleet variables such as VARIANT and FREQ and we have configuration info such as:
```
Define DT parameters
"i2c_arm=on","spi=on"
Define DT overlays
"spi1-3cs", "uart0,txd0_pin=32,rxd0_pin=33,pin_func=7"
```

ideally, for balena open fleets we would be able to have these auto-populate and/or somehow be set manually - perhaps in diagnostics?

**Comment by vpetersson** [comment]
It doesn't seem to be possible to do this out-of-the-box in the [image creation](https://www.balena.io/docs/reference/OS/configuration/#valid-fields) process at least.

**Comment by shawaj** [comment]
We do it with the config.txt and a loopback connection.

We could just do the same with a file called like nebra.txt or something and read back the details perhaps? Or if it doesn't break anything, put some custom stuff in config.txt

**Comment by vpetersson** [comment]
@shawaj I've scoped out the ticket for migrating `VARIANT` and `FREQ` [here](https://github.com/NebraLtd/hotspot-production-images/issues/23). I'm still not sure how to solve the SPI configuration, as this is set from within the dashboard. The only way I can think of is having separate fleets per device type (which wouldn't be too big of an issue).

**Comment by shawaj** [comment]
This has been sorted for open fleets by Balena.yml files

And the rest will be sorted by https://github.com/NebraLtd/hm-diag/issues/444

**Comment by shawaj** [comment]
Closing as completed
