### ISSUE TITLE
Miner not working on ETH anymore

### ISSUE THREAD

**Issue by kappa-london** [NebraLtd/helium-miner-software#167]
- [ x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Brand new miner out of the box. I connected it to my PoE and it was working fine it connected to the internet and started syncing. 

Today morning I made the setup and moved it to the balcony and it wont connect anymore. The board shows the blue light blinking 4 times in a pattern. Tried to restart but is stuck in this state.. I have 4 miners with the same exact problem. 

First i realised that my Router can not find the mind when is online .. and wont provide IP just 0.0.0.0 and then I saw the light blinking.

**To Reproduce**
1. Connect to PoE
2. Leave for a few hours
3. Disconnect the PoE
4. Connect again and is not working over ETH 

**Expected behavior**
Connect via Ethernet and work as expected

**Additional context**
Happened with 4 miners.. And 2 different PoE devices. TP-LINK PoE Injector - TL-PoE150S the same one from Nebra website.

**Comment by shawaj** [comment]
Please email support@nebra.com this is not for technical support

**Comment by kwsystems** [comment]
Hi,

@kappa-london I have the same problem. What did Nebra told you? It is been weeks that I sent them an email and no answer.

Thanks
