### ISSUE TITLE
Onboarding Issue - Green LED Off and Bluetooth Broken

### ISSUE THREAD

**Issue by Ryan-Goldstein** [NebraLtd/helium-miner-software#175]
- [X] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Shortly after powering up a newly delivered batch 3 indoor Nebra hotspot, I could connect via Bluetooth and start the onboarding process, with the external green LED blinking occasionally. However, after a few minutes, the external green LED goes out, potentially as the hotspot is updated to firmware version 2021.10.07.3, and it's no longer possible to pair via Bluetooth. The diagnostics page is still available by navigating to the local IP, but it shows "Diagnostics have not yet run, please try again in a few minutes". The external yellow LED and all internal LEDs are illuminated normally.

Power cycling, reseating all components, and letting it sit connected to the internet for hours, both via Wi-Fi and Ethernet, all do not resolve this issue.

**To Reproduce**
1. Start the onboarding process of an indoor Nebra hotspot by connecting via Bluetooth and to the internet.
2. After a few minutes, the external green LED will turn off, and Bluetooth will disconnect.

**Expected behavior**
The external green LED should continue to be illuminated and Bluetooth pairing should still be possible.

**Additional context**
Throughout the day today (October 19, 2021), a large number of people have been joining the (unofficial) Nebra Community Discord to report this issue, most of whom are also initially setting up their hotspots today and encountered this problem.

**Comment by shawaj** [comment]
this is not for support.

please email support@nebra.com

**Comment by rawrmaan** [comment]
We've got a meticulous process for onboarding Nebra hotspots to avoid issues and we're currently at a complete standstill due to this issue. The miner software never appears to boot so no diagnostic methods are useful.

**Comment by shawaj** [comment]
> We've got a meticulous process for onboarding Nebra hotspots to avoid issues and we're currently at a complete standstill due to this issue. The miner software never appears to boot so no diagnostic methods are useful.

That simply isn't possible. And we can't reproduce this issue on any units
