### ISSUE TITLE
Maintenance window

### ISSUE THREAD

**Issue by dowjames** [NebraLtd/helium-miner-software#178]
Can we please implement a maintenance window, like patch Tuesday or something? My hotspot has restarted 3-4 times in the last three days because of updates, causing all kinds of problems. 

Thanks

**Comment by vpetersson** [comment]
No, that isn't realistic this early in the Helium days. We need to be able to iterate quickly and both implement our own fixes and the upstream Helium fixes quickly. Restarts should really not cause any issues however.

**Comment by dowjames** [comment]
https://discord.gg/PZ6BrqF6
