### ISSUE TITLE
Document pre deployment tests on testnet

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#180]
Currently, we test releases on testnet for a period of time before bumping the production fleet to the new release, however this testing is somewhat changeable (depending on what has been updated) and doesn't always catch issues (especially minor regressions).

We should document a list of manual checks that should be performed on testnet devices (connecting to Bluetooth, running a diagnostics report, connecting and disconnecting WiFi etc etc) before a release is deployed from testnet into production.

This is a precursor, and a first step to fully automated deployment tests which will come in the future (see #181 )

@vpetersson and @KevinWassermann94 have already been discussing this

**Comment by shawaj** [comment]
@KevinWassermann94 think this is complete now right?

**Comment by KevinWassermann94** [comment]
@shawaj Yes, let's close this
