### ISSUE TITLE
Nebra indoor no green light, no internal diagnostics page on internal Ip, but pingable 

### ISSUE THREAD

**Issue by madlin** [NebraLtd/helium-miner-software#190]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Nebra indoor miner is pingable on network level. If I scan miner it says that tcp 80 is open. If I access the diagnostics page via webbrowser from multiple computers it says err_connection_refused. 

On the online dashboard it says connected to update server, but not connected to helium network. 

All internal diagnostics light show expected behavior.

External lights: Only yellow external light and no external green light. 

Same imaged flashed on other SD and booted shows exactly the same behavior. Raised a ticket with support with ticket number 289693.

**To Reproduce**
Flash my image on sd or emmc wil give the same behavior. I expect that aHard reset is needed and that this issue is related to a bug. Several users are complaining with same issue. Please do an analysis on this and execute a hard reset. 

**Expected behavior**
Green external light, connected to helium network and accessible diagnostic page on internal IP. Internal Ip is responding on icmp en webservice is running. 

**Screenshots**
If applicable see support ticket 289693.

**Desktop (please complete the following information):**
 Various desktops and mobile phones on same internal non filtered network. 
@vpetersson 
@shawaj

**Comment by Ryan-Goldstein** [comment]
I'm experiencing the same issue and followed the same troubleshooting steps. The hotspot appears online in the Nebra Dashboard and is pingable, but the external green LED does not illuminate at all since 2021.10.18.1 was released. Details here: https://www.reddit.com/r/HeliumNetwork/comments/qds6ol/nebra_firmware_issues_cannot_onboard/

**Comment by madlin** [comment]
Nicely written! I have exact same after relocating miner to other location. Since almost 2 weeks this behavior.

**Comment by quaineday** [comment]
Same problem here starting today. Power cycling and leaving the miner off for 30+ minutes usually brings it back. port scan on internal IP only shows tcp/22222 available. ICMP still responding and can see the traffic when sending those packets. No other traffic is coming from miner when plugged in.

**Comment by shawaj** [comment]
This is not a support channel.

Please email support@nebra.com

**Comment by madlin** [comment]
I already did a few times and no response.
