### ISSUE TITLE
eMMC key never sent!!! 

### ISSUE THREAD

**Issue by johnnybegood88** [NebraLtd/helium-miner-software#191]
I am fully aware that this is not for customer support, but Wayne just stopped replying to my emails two weeks ago after he said he would send me a new eMMC key (see email below). I have written 3 emails since and nobody got back to me. I am therefore trying my luck here. It cannot be that you send out non functioning miners, promise to replace the broken parts, but your customer service just doesn't get back to us...

"Hi Xavier,

OK I'll get your a new eMMC key out for the miner, so sorry about this, and you say you have the same issue with another miner? Could you do the same for that one and get me a picture of the inside when you can.

Thanks for the update on the location of the miners and sorry to hear about the issue with the heatsinks as well. It's been reported back to operations who deal with the production side of things. 

When you get your new eMMC key it's very similar to a micro SD card, Please power off the miner, remove the old one and then insert the new key, power back on the miner, and then allow to boot. (Please see picture attached) 

They should be getting posted out as soon as possible. 

Best wishes,
Wayne"

**Comment by shawaj** [comment]
We sent out a lot today. Thanks for your patience.

**Comment by johnnybegood88** [comment]
Don’t thank me for my patience, rather solve the problem and actually get them to reply! 


Liebe Grüsse, 

Xavier Fricker
***@***.*** ***@***.***>
_____

Tryo GmbH, www.tryo.ch <http://www.tryo.ch/>, Aeschenvorstadt 57, 4051 Basel

Disclaimer: Die Sicherheit Ihrer persönlichen Daten ist uns sehr wichtig. Die in dieser E-Mail enthaltenen Informationen sind vertraulich und ausschliesslich für den bezeichneten Adressaten bestimmt. Anderen Personen oder Organisationen, die nicht der vorgesehene Adressat dieser E-Mail sein sollten, ist  jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail untersagt. Sollten Sie diese Nachricht irrtümlich erhalten haben, bitten wir Sie, sich mit dem Absender der E-Mail in  Verbindung zu setzen und das Material von Ihrem Computer zu löschen.
