### ISSUE TITLE
New device Outdoor miner Gen 1 connected to internet and blockchain but auto-update firmware does not work,

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/helium-miner-software#197]
**Describe the bug**
New device Outdoor miner Gen one1 eth 00:BD:27:00:1A:B4  connected to internet and blockchain but auto-update firmware does not work, device Firmware 2021.09.27.0, will not auto-update nor does it appear to be updating sync with blockchain (though something is happening as the blockchain height continues to rise but no sync happening).  It has been connected for days an no real progress.

**To Reproduce**
Follow setup steps given on helium web 
https://helium.nebra.com/outdoor-hotspot/quick-start

as well as troubleshooting documentation
https://helium.nebra.com/outdoor-hotspot/troubleshooting

**Expected behavior**
The device should auto-update firmware AND fully sync with the blockchain. (I've waited many days and seen no progress, so not slow, just not working)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome - Latest
 - Version - Latest

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOs 15.1
 - Browser Chrome and Safari
 - Version Latest

**Additional context**
WiFi signal is good.  Traffic is seen in the wireless channel.

Tried with UPnP and no forwarding, tried with UPnP and forwarding.  No luck.

**Comment by shawaj** [comment]
Have just fixed your device, but please note that for future support requests you will need to email support@nebra.com

**Comment by millerz1897** [comment]
> Have just fixed your device, but please note that for future support requests you will need to email [support@nebra.com](mailto:support@nebra.com)

Thanks! When should I expect to see a change?  Doe this require a restart on my end?

**Comment by shawaj** [comment]
It should be fixed in the next half an hour or so :-)
