### ISSUE TITLE
Software Image

### ISSUE THREAD

**Issue by elapstor** [NebraLtd/helium-miner-software#198]
Hello, this is a question / suggestion,

Would it be possible to get a base image (.img) file similar to how sensecap has done it?

[ heres the link : https://drive.google.com/file/d/1fZf09U2_jQOpsSKPWc8TAZ_Jl82X9tzx/view ]

This would greatly help with upgrading the sd cards  (flashing new ones without cloning). If that's not possible maybe just a .txt with at least vague statements on how to do it without the .img file. 

For people that are familiar with balena and docker, the way to do this might be obvious, but for the people that are even a little "savvy". Some vague instructions can help significantly. (this could also help in reducing even a small portion of support tickets)

Thanks

**Comment by shawaj** [comment]
This is not supported and unless requested to do so specifically by our customer support team it will void your warranty
