### ISSUE TITLE
Hotspots went offline

### ISSUE THREAD

**Issue by florinvulpe** [NebraLtd/helium-miner-software#201]
Hi
For over 24 hours now I have 2 hotsport that went offline.  On app.heliumstatus.io also looks ok and have a great ping test but on explorer they are offline and 0 activity and API.helium.io/V1/hotspots also shows offline and when I try a discovery also impossible because it say that is offline
Both my devices are indoor.
On nebra dashboard at one shows syncing and on one in sync.

**Comment by florinvulpe** [comment]
Now on app.heliustatus.io i have this : 
![Screenshot_20211110-223233](https://user-images.githubusercontent.com/39153232/141189190-b3ab478e-72ee-4793-a9fd-d30dbbd9d93d.jpg)

**Comment by hugofmaximo** [comment]
Exact same thing over here. It would be great to have a solution for this.

**Comment by shawaj** [comment]
This is not a support channel. Please email support@nebra.com
