### ISSUE TITLE
blocked at Height Status	1091971

### ISSUE THREAD

**Issue by atartareanu** [NebraLtd/helium-miner-software#202]
Hello
Since yesterday my Nebra miner is blocked at Height Status	1091971. 
Sync Percentage | 99.88%
Connected To Helium Network: | No
Everything shows green on local diagnostics page.

I have tried multiple restarts, but nothing happens.
The disk usage will vary between 8.1GB and 8.3GB, meaning the miner is trying to do something, but without success.
checking the router for internet traffic I see way more usage than a normal mining day, around 11GB/hour as compared with a normal of 200MB/hour.
What's happening ?

Can you please fix this problem ? looks like an issue affecting a lot of people.

Thank you.

**Comment by hugofmaximo** [comment]
Showing the same here. Can we fat nebra to send an update to fix this?

**Comment by shawaj** [comment]
This is not a support channel please email support@nebra.com
