### ISSUE TITLE
Can't reboot miner inside dashboard, because its "offline"

### ISSUE THREAD

**Issue by yassing** [NebraLtd/helium-miner-software#204]
I can no longer reboot my nebra in the dashboard, because it says that the miner is offline. But the miner is online is the local dashboard and website. Before it was always possible to reboot the miner (My other miner also doesnt auto update to a higher snapshot, idk if this correlated)

Dashboard:
![image](https://user-images.githubusercontent.com/22550343/141219134-920caccb-352b-4f1e-8c60-b004ae496c45.png)

Miner is online

![image](https://user-images.githubusercontent.com/22550343/141219247-b18a0e7a-94f2-4b36-bb02-f41187ca6db1.png)

**Comment by shawaj** [comment]
This is not a support channel.

Please email support@nebra.com
