### ISSUE TITLE
Change CODEOWNERS and branch protections to suit new flow

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#208]
We should change CODEOWNERS and branch protections in this repo to match the release flow discussed by @KevinWassermann94 in the latest all hands

**Comment by shawaj** [comment]
Currently have set the branch protections as follows:

- **master** this branch is set to require a single CODEOWNERS review
- **production** this branch is set to require two CODEOWNERS reviews/approvals

With PRs being required and no direct pushing.

@KevinWassermann94 @vpetersson @marvinmarnold does this make sense to you?

**Comment by shawaj** [comment]
And just FYI CODEOWNERS includes developers and tech support teams...

**Comment by KevinWassermann94** [comment]
@shawaj Is there a way to make production need 1 approval/review by a dev + 1 more by the tech support?

**Comment by shawaj** [comment]
@KevinWassermann94 I'm not sure that's possible TBH

@vpetersson @marvinmarnold any ideas if this is possible?

**Comment by marvinmarnold** [comment]
It might be possible if we enable `Require review from Code Owners` in addition to `Require approvals`. Would need to test this a bit to confirm.
