### ISSUE TITLE
Tracking issue: update balena device OS from Nebra HNT to Raspberrypi3-64 ESR release

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#216]
This is a tracking issue which will need input mainly from @NebraLtd/tech-support to test updated devices on our testnet to ensure that they are working correctly.

## Update process

On individual devices you first need to change the device type to raspberry pi 3 64 bit by clicking on `Change device type`:
![Screenshot_20211113-171954_Chrome](https://user-images.githubusercontent.com/3359418/141653017-b8f57484-6764-4687-b085-720f12d0e536.jpg)
![Screenshot_20211113-172019_Chrome](https://user-images.githubusercontent.com/3359418/141653018-9bd7aa1f-8860-4dee-96a6-f533e6bdc6e9.jpg)

Once completed, you can then update the OS to the ESR release 2021.10.2 by clicking `Update balenaOS` and choosing balenaOS ESR and v2021.10.2:
![Screenshot_20211113-171114_Chrome](https://user-images.githubusercontent.com/3359418/141652974-485f3e82-ab17-4fa9-83c7-4f8aa600d8c8.jpg)
![Screenshot_20211113-171544_Chrome](https://user-images.githubusercontent.com/3359418/141652976-ad290307-8c64-4cb5-8eeb-9fcd39a5b53e.jpg)

## Test process

Once updated, the steps for testing testnet releases should be used to test everything is working ok.

**Comment by shawaj** [comment]
Have already updated weathered-pond, winter-wood, young-silence and delicate-sky on testnet.

@KevinWassermann94 can you and the team work on testing these and possibly some of your own devices to ensure that they work ok on the new OS version?

**Comment by KevinWassermann94** [comment]
@shawaj I will check through the devices Monday

**Comment by shawaj** [comment]
Awesome thanks @KevinWassermann94 

Basically same tests as done for new testnet devices with Bluetooth/config tests too would be amazing

**Comment by shawaj** [comment]
@KevinWassermann94 did you get a chance to test this any further?

**Comment by KevinWassermann94** [comment]
@shawaj The tests were going fine, but we were interrupted by the Helium network going down

**Comment by shawaj** [comment]
> @shawaj The tests were going fine, but we were interrupted by the Helium network going down

@KevinWassermann94 ah ok, fair enough!

Let me know if you notice any problems at all

**Comment by shawaj** [comment]
@KevinWassermann94 and @NebraLtd/tech-support have tested and apparently this is working fine (confirming my tests too)

**Comment by shawaj** [comment]
The vast majority of currently online units have been updated to raspberry3-64 2021.10.2 ESR release on balenaOS.

New hotspot production will be on the 2021.10.2 ESR release for Raspberry Pi 3 or on the 2021.10.3 ESR release for RockPi.

Will continue to update devices periodically as any older devices come back online but will close this issue for now
