### ISSUE TITLE
Nebra Outdoor Bricked after upgrade from 11.11 to 11.11-01

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/helium-miner-software#222]
- [X ] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**

Last night device was working but not this morning. Checked status via admin webpage and rebooted (knowing that there are larger problems with the helium network).

The device is pingable but HTTP returns error 500 - Internal Server Error

Device ID - 00:BD:27:00:1A:B4

**To Reproduce**
Upgrade from 11.11 to 11.11-01

**Expected behavior**
The device should function as intended.

**Screenshots**

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**

**Comment by shawaj** [comment]
the issue is the chain halt happening currently.

until that is resolved, the diag page will 500

**Comment by shawaj** [comment]
related to https://github.com/NebraLtd/hm-diag/issues/204
