### ISSUE TITLE
Feature Request: display helium outages in Diagnostics and Dashboard

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/helium-miner-software#223]
When there is a system outage, of any type including a chain halt, problems with the update server, etc. Nebra device should via the web console and dashboard make users aware of the issue, and, if known, any planned resolution time.

**Comment by marianpilka** [comment]
Bump the problem. Guys, really, what is going on with your devices... All Nebra hotspots seems to DO NOT WORK despite being online and without connection issues, verified with app.heliumstatus.io

**Comment by vpetersson** [comment]
This does not at all align with the data we're seeing from Helium Explorer based on customer deployments.

**Comment by Faraj-dev** [comment]
I just want to know why suddenly my hotspot went offline, and it has been in this state for at least 6 hours if not more. I have not done any reboot or disconnected the internet or etc...and I would like to clarify that it is not only a problem with my hotspot but also with many others.

**Comment by vpetersson** [comment]
This is not a support forum. Contact support@nebra.com.

**Comment by marianpilka** [comment]
It is what I see on the data gathering sites, about 1/3 of the deployed devices are offline.
Mine is online, but still does not work proprely, so I may assume, based also on other users claims (reddit, discords) that the number of not functioning devices is even bigger.
Aditionally, I have other devices and after the fix they all are working properly and earning, leaving only Nebra that has issues and currently is flatlined. That is why people tend to write here about it to draw your attention to this problem. 
If you communicated better with your customers nobody would need to do that.
