### ISSUE TITLE
Blockchain height not increasing after firmware update

### ISSUE THREAD

**Issue by andy210000** [NebraLtd/helium-miner-software#229]
Hi 

The miner is not increasing in blockchain height since the update, its 1000 blocks behind. Would you mind taking a look at this?

![image](https://user-images.githubusercontent.com/26556021/142240297-55c02287-d354-42db-8662-08e3c56811b4.png)

Thanks 

Andy

**Comment by shawaj** [comment]
Give it some time. The network is not in a good way.

Also, try rebooting to grab a newer snapshot

**Comment by andy210000** [comment]
hi @shawaj 

Tried a reboot i get the same issue. still stuck at 1099848
