### ISSUE TITLE
Stuck on block 1099848

### ISSUE THREAD

**Issue by andy210000** [NebraLtd/helium-miner-software#230]
Hi, 

I rasied this earlier but the ticket was closed , my miner is still at block 1099848 after hours. its got the new firmware but has done nothing at all to download anymore of the block chain.
![image](https://user-images.githubusercontent.com/26556021/142279663-c9e3b1c0-c0a3-4b76-ae77-3166d3d053e2.png)

Any ideas how to sort this?

Thanks

**Comment by ganey** [comment]
Mine appears stuck too (which is annoying, it's been fine for weeks), and a lot of the time diag isn't loading either, I just get 500 Interval Server Error.

I have the same firmware as you, but mine says: <html>
<body>


Miner Connected To Blockchain | False
-- | --



</body>
</html>

**Comment by shawaj** [comment]
New GA coming out soon. The network is still struggling.

https://engineering.helium.com/2021/11/17/blockchain-release-resuming-the-blockchain.html

**Comment by shawaj** [comment]
Also, if you reboot you should pull down a new snapshot
