### ISSUE TITLE
Lora Operational False

### ISSUE THREAD

**Issue by st3fan87** [NebraLtd/helium-miner-software#234]
Due to the firmware update and helium outage the lora modules are not working. And in worst case, broken (still have to test with a new module)

The dashboard on nebra's ip says lora operational false. There is no way to fix this problem. Rebooting doesn't help, reseating module doesn't help.

Is this a known but or should I worry that my devices are broken?

**Comment by shawaj** [comment]
Please email support@nebra.com with a picture of the device label so we can take a further look at it.

It does not mean there's a hardware issue, just that the concentrator can't start. Which is most likely a software issue

**Comment by shawaj** [comment]
It will not work unless you have an asserted location.

It also will not work with all RAK concentrators and we do not support devices with modified hardware like this
