### ISSUE TITLE
Local Diagnostic page - Internal Server error

### ISSUE THREAD

**Issue by andy210000** [NebraLtd/helium-miner-software#236]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Local Diagnostics page just shows Internal Server erro

**To Reproduce**
1. Go to 'Webpage and enter local ip address 
2. See error 

**Expected behavior**
Nebra diagnostics page to load

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shawaj** [comment]
Email support@nebra.com
