### ISSUE TITLE
SX1302 issues

### ISSUE THREAD

**Issue by st3fan87** [NebraLtd/helium-miner-software#254]
Since a few days my rak2287 in the nebra miners are not working. 2 of them show lora operational false.  Has it to do with the sx1302 fix from a few days ago?

Also, since the miners make an awfull squeeling noise I think there are problems with the powersupply print.

The previous 2 nebra lora modules also got fried, and now these rak 2287's are also not working. So 4 in total broken. 
 
I can't reach nebra support. Please help, can we get in contact to look into this problem? I spend hundreds to repair the device and it keeps breaking apart

**Comment by shawaj** [comment]
We don't support sx1302 officially currently and it's a known issue currently.

Nebra miners all use sx1301 so please revert to the concentrator you purchased it with

**Comment by shawaj** [comment]
Ref https://github.com/NebraLtd/hm-pktfwd/issues/70

**Comment by st3fan87** [comment]
Ah yes, buy the first nebra modules are broken and I cant get support on this

**Comment by shawaj** [comment]
You can get support by emailing support@nebra.com

Sx1302 / sx1303 will be officially supported soon as we will move to those chipsets eventually but but we have no exact ETA

**Comment by st3fan87** [comment]
> You can get support by emailing [support@nebra.com](mailto:support@nebra.com)
> 
> Sx1302 / sx1303 will be officially supported soon as we will move to those chipsets eventually but but we have no exact ETA

Thanks, but which sx1301 modules could i use? Then I can already order one at my local supplier, that will be faster to get the miner going again

**Comment by shawaj** [comment]
Recommend to use the official Nebra one.

If you have an issue with yours then please email support@nebra.com

Also, as a side note, #264 should be in testing in the next couple of days and should fix the sx1302/sx1303 functionality

**Comment by st3fan87** [comment]
> Recommend to use the official Nebra one.
> 
> If you have an issue with yours then please email [support@nebra.com](mailto:support@nebra.com)
> 
> Also, as a side note, #264 should be in testing in the next couple of days and should fix the sx1302/sx1303 functionality

Oh wow, thanks for the heads-up. Really appreciate your reply! 

_I understand the recommendation and I really do want the official ones but unfortunately had no success on support  for a couple of weeks. Supplier had the 2287 modules straight away:)_

**Comment by shawaj** [comment]
@st3fan87 it is working well on testnet so we will probably push it to production in the next few days (or when the next GA comes out)

**Comment by st3fan87** [comment]
> @st3fan87 it is working well on testnet so we will probably push it to production in the next few days (or when the next GA comes out)

Thanks again for letting me know. Can I offer any help, as in, is it interesting to Nebra if I share my miners MAC so the team could see/monitor how the sx1302 performs in the wild?

**Comment by st3fan87** [comment]
waiting patiently, I know many people have those sx1302's on their miners :)

**Comment by shawaj** [comment]
@st3fan87 should be live now

**Comment by st3fan87** [comment]
> @st3fan87 should be live now
thanks!

To bad discovery mode is disabled otherwise I could test if the lora module is up and running. Not seeing any witnesss beacons yet. So let's wait:)

**Comment by st3fan87** [comment]
Ah yes!! It's working :) many many thanks

_Side note. from the community I saw a few complaints come by from people that have to reboot their miners after a firmware update. They discover earnings are 0 and after a powercycle (10 minute power off and then on) then it suddenly works agains. Happens after every firmware update._
