### ISSUE TITLE
Address miners stuck after update

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#266]
Follow up to: https://github.com/NebraLtd/product-management/issues/28

Kevin's research: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1637626611214600?thread_ts=1637626611.214600&cid=C024BNQ1Y6T

**Comment by shawaj** [comment]
I sent balena some support requests about this also. Will post here when I hear back

**Comment by stunney** [comment]
Mine are stuck too.  Fix this!

**Comment by shawaj** [comment]
@stunney please email support@nebra.com

**Comment by bhuism** [comment]
@shawaj 20+ nebra miners (only) are stuck at block 1105424 since Saturday, nobody has a fix. Mailed sales (second time, no response in days) Ticket (#316131).

**Comment by shawaj** [comment]
This is not a support channel. Please email support@nebra.com

**Comment by shawaj** [comment]
FYI https://github.com/NebraLtd/helium-miner-software/issues/103#issuecomment-987574207

**Comment by shawaj** [comment]
Related to #311 possibly

**Comment by shawaj** [comment]
Closing this as we don't see it very often anymore with the update lock override on all fleets by standard
