### ISSUE TITLE
Block Stuck Issue @ 1105424 days after 2021.11.22.0 install.

### ISSUE THREAD

**Issue by millerz1897** [NebraLtd/helium-miner-software#275]
[X] I understand that this is only to report software bugs and **not** for customer support. 

A support request with Nebra was submitted. (Ticket #316204).  An automated email was received, reviewed, and I'm looking forward to a human response.

**Describe the bug**
Since the recent November outage/s, and 24  h+ after upgrade to 2021.11.22.0, my Outdoor Gen 1 has been stuck on block 1105424.

Configuration is the same as when it was working before the outage and seeing gigs of traffic moving and the blockchain rising.   Currently at 1111233.

Am aware of https://engineering.helium.com/2021/11/22/blockchain-release-sync-emergency.html that addresses 1,107,994 and as a precursor block, this may be related.

After a few days since 2021.11.22.0 it would seem this should be resolved and deserves more scrutiny from the dev team, with perhaps escalation to Helium devs,  as a number of online forums have Nebra reports of the same.  For example https://www.reddit.com/r/HeliumNetwork/comments/qzgjuj/nebra_stuck_at_block_1105424_reboot_or_wait

**To Reproduce**
Operate a Nebra Outdoor Hotspot Gen 1.

**Expected behavior**
Nebra Outdoor Hotspot Gen 1 miner should be able to process through the block with the engineered hotfix applied in 2021.11.22.0 and return to normal function.

**Screenshots**
Full diagnostic available in ticket submitted (#316204) with diagnostics JSON

**Desktop (please complete the following information):**
Irrelevant.

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**
Other than this issue, the hotspot appears working and intermittently works with ping and shows in-sync on Nebra dashboard however CPU usage remains high and consumption of storage from around 3 GB has grown to over 9GB.

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).

**Comment by millerz1897** [comment]
> This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).

Did you read the whole report and why it is believed to deserve consideration by development?

Multiple devices are hung in the same place and the Nebra brand seems to be a commonality.

In addition, if it is a larger issue, who is in the best position to handle both Nebra integration and escalation to Helium proper?

**Comment by vpetersson** [comment]
Yes. The initial assessment will be done by the support team and then escalated to the development team. My understanding that they are aware of this and are investigating and quantifying this at the moment.

**Comment by millerz1897** [comment]
> Yes. The initial assessment will be done by the support team and then escalated to the development team. My understanding that they are aware of this and are investigating and quantifying this at the moment.

If it is a known issue, of potentially wide impact, why would it not be appropriate to track and memorialize the resolution here so that I and others can at least be aware of status?

**Comment by shawaj** [comment]
This is a helium issue https://status.helium.com

![image](https://user-images.githubusercontent.com/3359418/143474982-28671591-523c-4767-a8bd-eda1fb9f414c.png)
