### ISSUE TITLE
Hotspots never recovered after the second major blockchain upgrade ~ week ago

### ISSUE THREAD

**Issue by dobrevnikolay** [NebraLtd/helium-miner-software#287]
- [ ] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).
I wouldn't have to report it here if you have **responded** to the customer support ticket: 316973
**Describe the bug**
2 hotspots are inactive for more than a week already. One of them for more than 10 days.

**To Reproduce**
After the second blockchain update ~week ago 2 of my hotspots never recovered.

**Expected behavior**
Hotspots should work.

**Screenshots**

![0-02-05-4127cbf531310069a85b74ca431f7f48c23ef77e191496206e6ee44d36beb795_9789fc9051165fa0](https://user-images.githubusercontent.com/12647334/144209088-a47139c7-97d3-41e4-bb06-976007fce882.jpg)

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).
