### ISSUE TITLE
Stuc on firmware 2021.09.27.0 

### ISSUE THREAD

**Issue by Deno82** [NebraLtd/helium-miner-software#313]
New miner, i could add it to my wallet and give it his location. Wont sync to blockchain and is stuc on firmware 2021.09.27.0. Block 1. See this kind of problems on discord. 

![IMG-20211217-WA0004](https://user-images.githubusercontent.com/95320030/146604950-a757e28c-b0a7-4990-a3c9-2826b0f48b24.jpg)

![Screenshot_20211217-213920_Chrome](https://user-images.githubusercontent.com/95320030/146605152-9f012ad8-e22f-409d-be7c-fa9397b5d929.jpg)

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).

**Comment by Deno82** [comment]
They dont reply

**Comment by vpetersson** [comment]
All support tickets are being replied but allow for a few days.
