### ISSUE TITLE
Miner not beaconing since 2021.12.14 update

### ISSUE THREAD

**Issue by rosus89** [NebraLtd/helium-miner-software#316]
Hi my miner stopped beaconing since 2021.12.14 update, still witnessing but checking activity log last sent beacons is on 13 December, 2021.12.14.0-1 doesn't seem to have fixed the issue.

Sync Percentage | 100%
Variant | Nebra Indoor Hotspot Gen 1

**Comment by KevinWassermann94** [comment]
Please send a mail to sales@nebra.com - this is not a support channel
