### ISSUE TITLE
What hardware is needed?

### ISSUE THREAD

**Issue by mattdawg321** [NebraLtd/helium-miner-software#32]
I have 
rasberry pi 4 2gb or more ram
64 gig memory card

Unsure if i need
LoRa concentrator from rakk?
packet forwarder (LoRa esp development board?) or will the rasberry pi be efficient at this 
 lorawan gateway?

Any input on this would be great, thanks!

**Comment by ganey** [comment]
Hey, i'm not part of the Nebra team, but hardware wise the Nebra devices appear to use a custom mainboard and a raspberry pi compute board.
 
If your goal is to earn HNT crypto then you're out of luck with a DIY solution as you'll need a security chip. You could however build a packet forwarder [based on the guide here](https://docs.helium.com/mine-hnt/build-a-packet-forwarder)

**Comment by shawaj** [comment]
yep you can run this on a pi3 / pi4 probably with some minor modifications. but you won't be able to mine HNT without an onboarded secure element chip
