### ISSUE TITLE
github action update triggering further github actions

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#338]
after #272 has been merged, there is an issue with the github action....because it is committing a new file to the repo it gets stuck in a circle of automatically deploying and updating the repo / deploying to balena

**Comment by shawaj** [comment]
we can stop this by changing MR_BUMP secret to GITHUB_TOKEN as per here - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#triggering-a-workflow-from-a-workflow

However, due to branch protection I am not sure it will be possible to directly push to master using this method

**Comment by shawaj** [comment]
looks like `paths-ignore` might work - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files

**Comment by SebastianMaj** [comment]
@shawaj Here is a solution I did a while back on hm-pyhelper when we had auto bumping version 
https://github.com/NebraLtd/hm-pyhelper/blob/b0dff572dfae1256ca724ba5337150b5ee7d6ecc/.github/workflows/publish-to-pypi-test.yml#L93

**Comment by SebastianMaj** [comment]
You could add some obscure keyword to the commit message when a push/change is automated and then simply ignore steps that are causing a loop if the push contains that keyword

**Comment by shawaj** [comment]
ahh nice - thanks @SebastianMaj that is useful. for now i just ignored the path in #339 

seems to work ok...guess pretty similar to your solution. not sure there are any particular benefits to either way - unless you can think of any?

**Comment by SebastianMaj** [comment]
I feel like your method has more benefits as it relies on the path instead of a message. Especially since it will only ignore the workflow if the whole commit only consists of files included in the paths-ignore.

>When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.

**Comment by shawaj** [comment]
Ok let's leave as is for now then. Can always change if it becomes a pain or a better way presents itself

**Comment by shawaj** [comment]
Closing for now based on #339
