### ISSUE TITLE
Miner diagnostics broken after latest update

### ISSUE THREAD

**Issue by kashifpk** [NebraLtd/helium-miner-software#343]
hm-diag is unable to fetch the device serial number and just keeps displaying a screen like:

![image](https://user-images.githubusercontent.com/198638/150167158-d5e4617a-8989-4d94-9fb9-b8b114d2a531.png)

The reason for this is the proc filesystem is not being mounted within the hm-diag container.

On the host container we're able access the serial number file

![image](https://user-images.githubusercontent.com/198638/150168218-f585f2bb-483d-4506-8a50-04665eead6e0.png)

But on the diag contain the `device-tree` folder is not present.

![image](https://user-images.githubusercontent.com/198638/150168426-0c79b989-7604-4956-a4ba-01b558f0cee9.png)

My guess is the we missed the proper permission or mapping in docker compose for proc for these containers. @SebastianMaj can you look at docker-compose file from production and compare it to what is being generated now to see if we haven't missed anything? @vpetersson - I remember that we need to allow access to pseudo filesystems like `/proc` and `/sys` to container explicitly. That's probably what we need to double check?

**Comment by SebastianMaj** [comment]
@kashifpk I'll do a difference check now to see if something was missed with the generation.

**Comment by SebastianMaj** [comment]
https://www.diffchecker.com/bbGztAxj

I see that privileged flag is missing, let me see if this is the cause of the issue

**Comment by SebastianMaj** [comment]
I'm getting the same error on my side running the changes on master branch so I'm deploying this locally with privileged: true on diagnostics container as well to verify

**Comment by SebastianMaj** [comment]
I was able to load up the diagnostics page after adding this line, I'll open a PR

**Comment by shawaj** [comment]
nice find @SebastianMaj @kashifpk
