### ISSUE TITLE
Don't commit final output files to ` device-compose-files/*.yml`

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/helium-miner-software#345]
When reviewing https://github.com/NebraLtd/helium-miner-software/pull/341, I noticed that we are committing the output files from the generator to `device-compose-files/*.yml`. This doesn't make any sense to me. We should simply generate these files on the fly and then throw them away. I don't see any need to commit them.

**Comment by shawaj** [comment]
This was done intentionally for audit purposes

**Comment by shawaj** [comment]
See discussion on #272 for discussion

**Comment by shawaj** [comment]
Oops pushed the wrong button there.

General gist was that it's useful to have these user-readable in the repo and there's no real reason not to...

**Comment by vpetersson** [comment]
We already spit them out to the stdout on the Actions flow so we have a paper trail of them already.

**Comment by shawaj** [comment]
Yeah but that's not publicly available

**Comment by shawaj** [comment]
closing this as doesn't seem to cause any harm
