### ISSUE TITLE
Extremely high bandwidth usage

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#353]
Convo: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1642627401172200
Related to: https://github.com/helium/miner/issues/1374

**Comment by shawaj** [comment]
@marvinmarnold was this due to a snapshotter error perhaps? is this still occuring or can we close this issue and the one on the helium repo?

**Comment by marvinmarnold** [comment]
@shawaj do you know the average bandwidth consumption we expect? I have two miners plugged in most times. Not a whole lot of non-work traffic on my home network but usage still seems high. I had to upgrade to an unlimited plan.
![Screen Shot 2022-03-01 at 3 14 51 PM](https://user-images.githubusercontent.com/1311030/156250346-879535a5-e9f5-44a5-bb41-3464625c9ada.png)
![Screen Shot 2022-03-01 at 3 14 31 PM](https://user-images.githubusercontent.com/1311030/156250350-ff3fb217-f439-448b-a104-16994ce97790.png)

I agree that a good portion of this is largely due to snapshotter.

**Comment by shawaj** [comment]
Yeah that seems pretty damn high. Expected to be around 50gb per month I think.

But to be honest I think this is likely down to the snapshot functionality in the helium miner code itself so not sure there's anything we can do about it.

It does seem really high though

**Comment by marvinmarnold** [comment]
@NebraLtd/device-team can you also post your recent bandwidth for comparison? Would be very interested in seeing before/after from people who recently got a miner.

**Comment by posterzh** [comment]
@marvinmarnold I noticed the Ethernet LED of my Indoor miner constantly was always blinking and consuming bandwidth, so I had to power off the miner. I have no report about the network usage of my miners, but even till nowadays, miner consume the network bandwidth a lot.

**Comment by kashifpk** [comment]
Mine looks ok, some ethernet activity but that's probably because of the diagnostics home page being open and refreshing.

![image](https://user-images.githubusercontent.com/198638/157048024-92b66eb6-fa51-4154-ac87-1fb5cbde8013.png)

![image](https://user-images.githubusercontent.com/198638/157048078-eb180c3f-01da-4c87-a57c-1fd7cd7adb9e.png)

The spikes on these graphs are expected and not from the miner so no unusual activity at my end.

**Comment by pritamghanghas** [comment]
I am on an unlimited plan. My provider shows only about 24 hours of history
for unlimited plans in their customer dashboard. And I don't have anything
setup locally for tracking it. Last 24 hours is barely 4gb.

Regards,
Pritam

**Comment by MuratUrsavas** [comment]
Mine is looking fine. Actually, too fine. 1,29 GB download and 0,45 GB upload for 6 days. I guess we have stopped using internet :smile: (Obviously our IPTV is not added to the sum)

**Comment by KevinWassermann94** [comment]
3 of my units are between 21GB to 25GB since beginning of the month. So probably around 50GB per month
