### ISSUE TITLE
Incorrect 'Region Plan' reported on local dashboard (maybe blocking Lora traffic).

### ISSUE THREAD

**Issue by snip** [NebraLtd/helium-miner-software#358]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
A clear and concise description of what the bug is:

On a Nebra outdoor, local dashboard was showing 'EU868' for 'Region Plan'. But on an other hotspot with same Firmware Version it was showing 'region_eu868' for same field.

A reboot of the one showing 'EU868' via the Nebra dashboard has put the value back to 'region_eu868'.

It seems that during the time the value was visible as 'EU868' it was not able to receive Lora messages. (at least it was not able to route join messages).

**To Reproduce**
1. Unknown. (Maybe after a power outage)
2. Check on the local dashboard value of 'Region Plan'

**Expected behavior**
Having Lora trafic routed without the need of rebooting the Nebra.

**Screenshots**
Before reboot :
![image](https://user-images.githubusercontent.com/466133/151413228-6a533256-65fc-41a9-bbc1-c72e9807f806.png)
After reboot :
![image](https://user-images.githubusercontent.com/466133/151413183-33feb14c-a2bc-4575-8f1d-30350894b826.png)

**Additional context**
Issue was encountered wit h firmware 2022.01.12.1-3 (or earlier. I'm not sure if there was an upgrade since i observered the issue).
I observed the issue today (2022.01.27), but also in the past weeks.

Thanks

**Comment by shawaj** [comment]
This is not a support channel.

Please email support@nebra.com

**Comment by snip** [comment]
This is not a support issue. I do not have anymore issue.
Just reporting bad behavior.
