### ISSUE TITLE
Nebra Error Miner Rpc Unavailable

### ISSUE THREAD

**Issue by newdevilus** [NebraLtd/helium-miner-software#365]
Hello. My device has had the message Miner RPC Unavailable from 03.02.2022.
 I restarted, reboot, stopped, turned on, the same message.I physically check inside seems okay.
Some intruction how to resolve?
Please help.

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).
