### ISSUE TITLE
Miner RPC Unavailable & RAM Full

### ISSUE THREAD

**Issue by Jomop** [NebraLtd/helium-miner-software#366]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**

After the recent chain halt, lots of users experience the “Miner RPC Unavailable” and really high RAM usage on the dashboard.

In the **UNOFFICIAL** discord server, the following guide was posted to fix this.

https://www.reddit.com/r/HeliumNetwork/comments/r2pqq6/your_nebra_miner_is_still_not_syncing_here_is_a/

The user states:

“What I think happened is that the big block somehow crashed the helium mining container (because the miner ran out of RAM) and one of the databases that stores the blockchain got corrupted during the crash. Now when the mining container starts, it tries to repair the database and fails.”

His solution was to: 

“Navigate to resin-data/docker/volumes/1804672_miner-storage/. You should see a a folder called _data. You can now either delete the folders content entirely or just rename it to something like _data.old and create a new empty _data folder. Whatever you do, make sure an empty _data folder exists after you're done or your miner still won't work.”

If what stated is accurate, I’d recommend a health check for the database repair failure and an automated purge of the _data folder contents. 

Hope this helps.

**Comment by vpetersson** [comment]
This is not an endorsed fix. Modifying the miner (e.g. enabling SSH and making changes) does void the warranty and you're on your own.

**Comment by Jomop** [comment]
@vpetersson yes, obviously. That’s why I haven’t performed it on my units and am instead pointing it out here in case it helps. It would be great to know, if you’re looking at this from your side.

**Comment by vpetersson** [comment]
We have implemented the upstream fixes for this ([Blockchain Garbage Collection](https://engineering.helium.com/2021/12/30/blockchain-release-snapshot-loading-and-storage-improvements.html)), which appears to permanently resolve this storage issue. There may be some devices that are still stuck on a previous firmware and thus exhibit the behavior above, but this should be reported to Support and they can rectify this issue.
