### ISSUE TITLE
Automate RAK deployment

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#367]
- Create Balena fleets for every region
- Automate testnet and production workflows

**Comment by MuratUrsavas** [comment]
@vpetersson or @marvinmarnold, could you create following fleets?

1. nebraltd/helium-rakv2-470
1. nebraltd/helium-rakv2-868
1. nebraltd/helium-rakv2-915

**Comment by MuratUrsavas** [comment]
AFAIK RAK v1 is not ECC compatible. That's why I thought adding v2 could be a good idea. if RAK is OK, then we can use these:
1. nebraltd/helium-rak-470
1. nebraltd/helium-rak-868
1. nebraltd/helium-rak-915

**Comment by vpetersson** [comment]
Done.

**Comment by MuratUrsavas** [comment]
@vpetersson If we've created the necessary configuration (adding `spi0-1cs` dtoverlay param for the fleets), we can close this issue.

**Comment by marvinmarnold** [comment]
@MuratUrsavas can you close this?
