### ISSUE TITLE
nebra does not work.

### ISSUE THREAD

**Issue by manipayment** [NebraLtd/helium-miner-software#369]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
Don't worry if your device hasn't been testifying for 3 months

**To Reproduce**
1. Send an email to Support
2. open a ticket
3. search for solutions to the problem on the forums
4. nebra doesn't answer.
5. nebra will sell you a new emmc key. 
6. the miner will not work again.
7. now it's 1. go back to the matter.

**Expected behavior**
Stand behind the product you are selling, either give me my money back, or repair this miner.

**Screenshots**
![Ekran Resmi 2022-02-15 18 12 33](https://user-images.githubusercontent.com/99134090/154090801-acc52b8d-915a-4b17-89c3-df947281a54d.png)

**Comment by vpetersson** [comment]
This is not a support forum. Please contact [support@nebra.com](mailto:support@nebra.com).
