### ISSUE TITLE
Validate all hat/concentrator combinations on MNTD

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#375]
**Acceptance criteria**
- Try on RAK ROCK Pi varying concentrator: Nebra sx1301, sx1302, sx1303
- Swapping Nebra hat
- Swapping hat and all concentrator variants
- Check for
  - Witnesses
  - Beacons
  - Button starts Bluetooth advertisement
  - Diagnostics page only lists LTE as error
  - Can pair with app

**Comment by MuratUrsavas** [comment]
I thought it should be validated with all RAK concentrators, not the Nebra ones. My bad :sweat_smile:

**Comment by vpetersson** [comment]
@marvinmarnold the use case for this is to largely support the default concentrator. I don't think there is a big use case for using this with replacement concentrators.

**Comment by marvinmarnold** [comment]
Ya you are right @vpetersson. I think I created this in response to [this comment](https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1645477937807799?thread_ts=1645447498.348779&cid=C024BNQ1Y6T). Now that the ROCK Pi issue is resolved, I don't think this adds any value and can be closed.

**Comment by shawaj** [comment]
closing in favour of #376
