### ISSUE TITLE
Validate all hat/concentrator combinations on RAK v2

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#376]
**Acceptance criteria**
- Try on RAK ROCK Pi varying concentrator: Nebra sx1301, sx1302, sx1303
- Swapping Nebra hat
- Swapping hat and all concentrator variants
- Check for
  - Witnesses
  - Beacons
  - Button starts Bluetooth advertisement
  - Diagnostics page only lists LTE as error
  - Can pair with app

**Comment by shawaj** [comment]
@KevinWassermann94 would you be able to handle this once you receive the concentrators? do you have a mntd?

**Comment by KevinWassermann94** [comment]
@KevinWassermann94 Yes I have a MNTD I can use for this

**Comment by KevinWassermann94** [comment]
@shawaj @marvinmarnold I'll start off testing today/ tomorrow. I'll probably leave all combinations running for around 12 hours.
To match the acceptance criteria though, we probably need https://github.com/NebraLtd/hm-config/pull/174 on the Testnet first (Button starts BT advertisement)

**Comment by shawaj** [comment]
@KevinWassermann94 I'll bring those updates into #391

**Comment by marvinmarnold** [comment]
@shawaj could you remind me what we are trying to determine with these tests

**Comment by shawaj** [comment]
I think mainly it was just to verify that all hardware variables work and don't cause issues with packet forwarder etc.

Sort of just a bug finding mission in a sense

**Comment by shawaj** [comment]
@KevinWassermann94 @marvinmarnold think we can close this for the time being?

**Comment by KevinWassermann94** [comment]
@shawaj All combinations are working fine, except for the BT button with the RockPi hat on the RasPi and the other way around ofc.

**Comment by shawaj** [comment]
Ah I see what you mean yeah, as button will be on the wrong GPIO as per hm-pyhelper

Ok will close this for now then 👍
