### ISSUE TITLE
Hotspot online, sending beacons but not receiving witnesses.

### ISSUE THREAD

**Issue by MarcDietschi** [NebraLtd/helium-miner-software#379]
Issue as the title says (and it also has a Bluetooth connection interruption around 1 minute after reboot, also the button is not functional) with my Nebra Rock Pi 4 Indoor Miner: Firmware Version | 2022.02.22.0 (8465d62)

**Comment by KevinWassermann94** [comment]
Please reach out to sales@nebra.com
