### ISSUE TITLE
Proposal: Using hm-pyhelper as submodule in all repositories

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/helium-miner-software#394]
It is really hard to test the changes of hm-pyhelper repo as it requires releasing untested code and bumping it in all other repos. I'm suggesting to use it as git submodule.

**Comment by kashifpk** [comment]
@MuratUrsavas - You can just take whatever updated dev branch for hm-pyhelper you are interested in and locally install it using `python -m pip install -e .`. This way you don't need to install it from pypi and check your code against it. Once you feel everything is ready you can push to master (which would deploy to pypi).

I'd rather not introduce a different git mechanism if we have a way around it.

**Comment by kashifpk** [comment]
@MuratUrsavas - Regarding github workflows, things should really go there after testing locally so what we usually do is that we deploy hm-pyhelper after local testing and before deploying code in repos that  depend on new hm-pyhelper version.

I'd love to know about what kind of use cases force you to have a deployed hm-pyhelper version during development. One thing I can think of would be the need to deploy custom code into miner using `balena deploy`. But then wouldn't we be breaking all other repos where the sub-module is being used if it contains backwards incompatible changes?

If you can highlight use cases where "shared" sub-module solves the issue and we can't do that using current mechanism, that would be great.

**Comment by shawaj** [comment]
You can also just update from the container from the balena dashboard etc. That's how I tend to do it as I am lazy and don't have many units at home

**Comment by MuratUrsavas** [comment]
Yea, actually haven't thought about that. But I'm not sure whether this could help on container startup as it would revert to the default state.

Is there a way to make this change persistent?

**Comment by shawaj** [comment]
Not as far as I know. However maybe we could put an OVERRIDE_PYHELPER variable in that we can add in balena to do the install/ update at container startup?

**Comment by MuratUrsavas** [comment]
> One thing I can think of would be the need to deploy custom code into miner using balena deploy

This is what device team is always up to :smiley: No local support, unfortunately.

> But then wouldn't we be breaking all other repos where the sub-module is being used if it contains backwards incompatible changes?

That's the beauty of a submodule. It doesn't change unless you bump it on purpose. Doesn't matter what happens in other repos. We'll keep the same release style, just will use directly the code as subrepo. That will make testing a breeze without worrying to break anything.

A breaking change probably would occur much less frequently IMHO.

**Comment by shawaj** [comment]
You wouldn't need to release it. You could just install from the build artifacts in the pyhelper repo

**Comment by MuratUrsavas** [comment]
Yea, but isnt't that too complicated?

**Comment by MuratUrsavas** [comment]
In the end, this is just an idea, a proposal. Maybe we need more opinions?

**Comment by shawaj** [comment]
> Yea, but isnt't that too complicated?

Perhaps, that's probably more for others to decide. I was just throwing the idea out really.

To me a python package seems the "right" way to do it but that doesn't necessarily mean it's the best in this instance.

But if it's just for local testing I don't see how it's any easier to do a submodule than it is to use the release artifacts. As the release artifacts get built automatically on every PR

**Comment by MuratUrsavas** [comment]
While the containers are built, CI system will fetch the temporary branches of hm-pyhelper and use them to build the container. No release would happen. An error? Just fix and push it again to see the change. No release. Then after finishing the change, create a PR, merge to master and release as usual. Then bump the submodule in the necessary repo like bumping requirements.

Scenario would not change whether local, remote or fully automated. Temporary changes would remain temporary.

**Comment by shawaj** [comment]
I don't really see how that's much different to just using a built package from build artifacts in requirements.txt

Seems harder if anything

**Comment by kashifpk** [comment]
@MuratUrsavas - you can specify a github path/branch for installing packages using pypi. See https://pip.pypa.io/en/stable/topics/vcs-support/

With this you can build containers that use pyhelper directly from your git branch/commit. Wouldn't this solve your issues?

**Comment by MuratUrsavas** [comment]
These are all making the development more complicated than necessary and keeping pypi.org in the loop. IMHO it is much easier with submodules.

I understand, this is like the "tabs vs spaces" holy war. Submodules are another controversial topic. But I still prefer them due to their flexible and easy to use nature.

**Comment by vpetersson** [comment]
Submodules definitely come with their own drawbacks. Pip install targeting a particular has does offer best of both world I think. For this use case, installing from pypi doesn't add many benefits IMHO.

**Comment by kashifpk** [comment]
Specially when we do deploy hm-pyhelper as a library on pypi, trying to use it both as sub-module and package is just unnecessary complexity. Unless there is a solid use case where use a git hash for installation doesn't work @MuratUrsavas ?

**Comment by MuratUrsavas** [comment]
We wouldn't be using pypi releases if we'd switched to submodules. It would be released just for public usage.

Since I'm the only vote for the submodule, it's not feasible to discuss this further. Thanks for the discussion and ideas.

**Comment by kashifpk** [comment]
Thank you @MuratUrsavas  for raising the discussion. I hope you continue to do the same in the future too :-)
