### ISSUE TITLE
RAK and OG Miner issues (Fleet on Balena)

### ISSUE THREAD

**Issue by arduino43** [NebraLtd/helium-miner-software#396]
Deployed the RAK firmware (v2) and OG Miner firmware.

Both are failing in Balena. The diagnostic container faults and causes the pkt-forwarder and helium-miner to stop.

 diagnostics  2022-03-12 01:27:47,597 - [INFO] - hw_diag.utilities.quectel - (quectel.py).ensure_quectel_health -- /opt/python-dependencies/hw_diag/utilities/quectel.py:(404) - skipping quectel firmware update because UPDATE_QUECTEL_EG25G_MODEM is not set
 diagnostics  INFO:hw_diag.utilities.quectel:skipping quectel firmware update because UPDATE_QUECTEL_EG25G_MODEM is not set
 diagnostics  INFO:apscheduler.executors.default:Job "get_app.<locals>.run_quectel_health_task (trigger: interval[1:00:00], next run at: 2022-03-12 02:25:44 UTC)" executed successfully
 helium-miner  Diagnostics container not ready. Going to sleep.
Restarting service 'packet-forwarder sha256:8fb6af555f8cec6f080be3d6d15ce487305078a957e2851460b8c23c2f91d100'
 packet-forwarder  Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'
Service exited 'packet-forwarder sha256:8fb6af555f8cec6f080be3d6d15ce487305078a957e2851460b8c23c2f91d100'
 gateway-config  Diagnostics container not ready. Going to sleep.
 helium-miner  Diagnostics container not ready. Going to sleep.
 helium-miner  Diagnostics container not ready. Going to sleep.
 diagnostics  [2022-03-12 01:28:44 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:501)
 diagnostics  [2022-03-12 01:28:44 +0000] [501] [INFO] Worker exiting (pid: 501)
 diagnostics  [2022-03-12 01:28:44 +0000] [507] [INFO] Booting worker with pid: 507
 diagnostics  2022-03-12 01:28:46,018 - [WARNING] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(37) - Variant None is not recognized. Omitting --path arg.
 diagnostics  WARNING:hm_pyhelper.miner_param:Variant None is not recognized. Omitting --path arg.
 diagnostics  2022-03-12 01:28:46,828 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(47) - gateway_mfr response stdout: b'{\n  "result": "fail",\n  "tests": [\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "serial"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(data)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(config)"\n    },\n    {\n      "output": "invalid slot: 15",\n      "result": "fail",\n      "test": "slot_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "key_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "miner_key(0)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "sign(0)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "ecdh(0)"\n    }\n  ]\n}\n'
 diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stdout: b'{\n  "result": "fail",\n  "tests": [\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "serial"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(data)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "zone_locked(config)"\n    },\n    {\n      "output": "invalid slot: 15",\n      "result": "fail",\n      "test": "slot_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "key_config(0..=15, ecc)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "miner_key(0)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "sign(0)"\n    },\n    {\n      "output": "ok",\n      "result": "pass",\n      "test": "ecdh(0)"\n    }\n  ]\n}\n'
 diagnostics  2022-03-12 01:28:46,829 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(49) - gateway_mfr response stderr: b''
 diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stderr: b''
 diagnostics  INFO:apscheduler.scheduler:Scheduler started
 diagnostics  DEBUG:apscheduler.scheduler:Looking for jobs to run
 diagnostics  DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
 diagnostics  INFO:apscheduler.scheduler:Added job "get_app.<locals>.run_ship_diagnostics_task" to job store "default"
 diagnostics  INFO:apscheduler.scheduler:Added job "get_app.<locals>.run_quectel_health_task" to job store "default"
 diagnostics  DEBUG:apscheduler.scheduler:Looking for jobs to run
 diagnostics  /opt/python-dependencies/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
 diagnostics    return tzinfo.localize(dt)
 diagnostics  DEBUG:apscheduler.scheduler:Next wakeup is due at 2022-03-12 01:30:47.251052+00:00 (in 119.999167 seconds)
 diagnostics  DEBUG:apscheduler.scheduler:Looking for jobs to run
 diagnostics  DEBUG:apscheduler.scheduler:Next wakeup is due at 2022-03-12 01:30:47.251052+00:00 (in 119.976883 seconds)
 diagnostics  DEBUG:flask_caching.backends.simplecache:get key 'view//json' -> miss 
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2022-03-12 01:28:47,288 - [WARNING] - hw_diag.utilities.hardware - (hardware.py).detect_ecc -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(194) - Unable to lookup storage bus from hardware definitions, falling back to the default. Exception message: Variant None is not recognized.
 diagnostics  WARNING:hw_diag.utilities.hardware:Unable to lookup storage bus from hardware definitions, falling back to the default. Exception message: Variant None is not recognized.
 diagnostics  2022-03-12 01:28:47,324 - [WARNING] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(37) - Variant None is not recognized. Omitting --path arg.
 diagnostics  WARNING:hm_pyhelper.miner_param:Variant None is not recognized. Omitting --path arg.
 diagnostics  2022-03-12 01:28:47,423 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(47) - gateway_mfr response stdout: b'{\n  "key": "XXXXXXX",\n  "name": "jolly-XXXX-XXXX",\n  "slot": 0\n}\n'
 diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stdout: b'{\n  "key": "XXXXXXX",\n  "name": "jolly-XXXX-XXXX",\n  "slot": 0\n}\n'
 diagnostics  2022-03-12 01:28:47,424 - [INFO] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(49) - gateway_mfr response stderr: b''
 diagnostics  INFO:hm_pyhelper.miner_param:gateway_mfr response stderr: b''
 helium-miner  Diagnostics container not ready. Going to sleep.
Restarting service 'packet-forwarder sha256:8fb6af555f8cec6f080be3d6d15ce487305078a957e2851460b8c23c2f91d100'
 packet-forwarder  Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'
Service exited 'packet-forwarder sha256:8fb6af555f8cec6f080be3d6d15ce487305078a957e2851460b8c23c2f91d100'
 helium-miner  Diagnostics container not ready. Going to sleep.
 helium-miner  Diagnostics container not ready. Going to sleep.

**Comment by vpetersson** [comment]
You need to define `VARIANT` as en environment variable matching what's in [hardware_definitions.py](https://github.com/NebraLtd/hm-pyhelper/blob/master/hm_pyhelper/hardware_definitions.py), e.g. `COMP-RAKHM`.
