### ISSUE TITLE
OG Helium Miner (Pi3)

### ISSUE THREAD

**Issue by arduino43** [NebraLtd/helium-miner-software#397]
Some OG miners are the Pi3 board (all of mine are) and not the Pi4 board.

Is it possible to update to allow usage with these variant of the OG miner?

**Comment by shawaj** [comment]
@arduino43 thanks for the report - do you know if it is possible to tell programatically if they are pi3 or pi4? if not, we may need to just create a new fleet

but any info you could provide would be useful? such as pictures of the hotspot, what frequency you are etc etc

**Comment by arduino43** [comment]
Not 100% sure if you can tell programatically. All of mine are US915.

Originally all Pi3 board but due to sync issues I replaced all with Pi4. I forked the Balena fleet for the OG-Pi4 and installed on a Pi3 and it seems to be running without any issues.

I've attached two pictures. The only external difference between them is the location of the ethernet port, which on the Pi4 is closer to the antenna port (see photos).

Pi3:
http://klasjord.com/sites/default/files/inline-images/IMG_20200102_133557.jpg

Pi4:
https://preview.redd.it/wjkllm562uk51.jpg?auto=webp&s=e93b041008fee3207b27d3ba36705aeac57b5264

**Comment by shawaj** [comment]
This should be fixed by #408 

@arduino43 can you confirm?
