### ISSUE TITLE
Need to suppress CP15_barrier log lines

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/helium-miner-software#400]
It is flooding the logs and makes low level inspections quite difficult.

**Acceptance Criteria**
* There should be only limited amount of **CP15_barrier** logs after a reboot. It should stop right after container startup.
* `cat /proc/sys/abi/cp15_barrier` command has to output as `2` on host system after the containers started working normally

**Comment by shawaj** [comment]
@MuratUrsavas Balena have done this already

**Comment by shawaj** [comment]
https://github.com/balena-os/balena-rockpi/pull/53

**Comment by MuratUrsavas** [comment]
Yea, I'd seen that before. But it's yet to be released AFAIK. This one has been opened for a faster solution at our side.

**Comment by MuratUrsavas** [comment]
I'm closing this issue since the method is not effective against current scenario. If I could get an update from Balena, I'd open it back.
