### ISSUE TITLE
Light miner: Remove dbus container

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#401]
upnp removal: https://github.com/NebraLtd/hm-diag/issues/322

**Acceptance criteria**
- dbus container removed from helium-miner-software

**Comment by shawaj** [comment]
> @shawaj can you explain exactly why we no longer need session dbus? I understand why we don't need upnp.

Because this doesn't communicate over dbus and never will.

It uses gRPC for communicating with gateway config

**Comment by marvinmarnold** [comment]
Thanks. My doubt is because dbus is still used for Bluetooth pairing in config and ModemManager in diag. Couldn't remember if they also depended on the dbus container.

**Comment by shawaj** [comment]
@marvinmarnold I believe they are using the system bus from the host OS but certainly worth verifying that
