### ISSUE TITLE
Wi-Fi BT Gatt request on Pixel 5(?) Erroring out

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/helium-miner-software#41]
A customer has had the Wi-Fi BT GATT Request issue on a Pixel 5.

I believe this was fixed however requires some more investigation as it's happening again.

It did work for the customer on a Pixel 4.

**Comment by shawaj** [comment]
@posterzh think we solved this in hm-config but not sure?

**Comment by posterzh** [comment]
@shawaj @ryanteck Can you give me more information about the issues, such as screenshot, error message, etc?
