### ISSUE TITLE
Spike: Run light miners on Helium testnet

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#410]
Follow these instructions: https://docs.google.com/document/d/1ZENpXrNmAcJoPIRwGVSc96tyclNTbJWZCgzc0S9vYvA/edit

**Acceptance criteria**
- Deploy at least one ROCK Pi, RPi indoor, and RPi outdoor to testnet
- Determine if helium/miner can be run in this manner when light miners go live

**Comment by marvinmarnold** [comment]
# ROCK Pi
- Balena: https://dashboard.balena-cloud.com/devices/f00da3b83b8bc879fed1927c1bfecde8/summary
- AddGateway hash: Kv04OFkYZBUnkFM9ILtIxHn1IY8PAQP6sUpyOAdXeOo
- Identity:


```
{
  "key": "1ZF2HSYMRdjdk2tsCiAzjt8HxEAB2bY7NTQ7s5Jf4j9ahfGSBRf",
  "name": "wonderful-misty-pig"
}
```

# RPi Indoor
- Balena: https://dashboard.balena-cloud.com/devices/6e54f41d04eec1886cd89eea6ca61f08/summary
- AddGateway hash: kD_GB-W7onpVSKUDmPjA1W9R6SB-U9egWrPMkKabvho
- Identity:


```
{
  "key": "1Zx68c1ghuwd7UCWqvCKTgFxR1ZvfBLSk4suQnmFRHVw4o4yKev",
  "name": "faithful-oily-wren"
}
```

# RPi Outdoor
- Balena: https://dashboard.balena-cloud.com/devices/fd5f350f18f50c45a1a23eeb1a3170da/summary
- AddGateway hash: Anamg443k2gIW-N2FGVRtOdRbHY1bZxHW0DbqwJO6JI
- Identity:


```
{
  "name": "thankful-wintergreen-wren",
  "key": "1YwZHCKQhdZ3HgjmHuxVAwmuVedX9BqxLq4KzeWTJ638JqpYCiF"
}

```

Commands for future reference:
```
# Create wallet
$ ./helium-wallet create basic --network testnet
$ ./helium-wallet info

# AddGateway
$ WALLETADDRESS=[copy]
$ miner txn add_gateway owner=$WALLETADDRESS --payer $WALLETADDRESS --staking_fee 4000000 --fee 65000
$ ADD_GATEWAY_OUTPUT=[copy]
$ ./helium-wallet hotspots add $ADD_GATEWAY_OUTPUT --commit

# AssertLocation
$ ./helium-wallet hotspots assert --gateway [gateway_address] --elevation [5] --gain [3] --lat=[latitude] --lon=[longitude]

# Get PK
$ /opt/miner/lib/miner-0.1.0/priv/gateway_rs/helium_gateway -c /opt/miner/lib/miner-0.1.0/priv/gateway_rs/ key info

```

**Comment by marvinmarnold** [comment]
Testnet was previously down while onboarding the devices. It was restored today. Will continue to monitor these devices according to https://github.com/NebraLtd/hnt-products/issues/7.

# ROCK Pi
- wonderful-misty-pig
- https://testnet-explorer.helium.com/hotspots/1ZF2HSYMRdjdk2tsCiAzjt8HxEAB2bY7NTQ7s5Jf4j9ahfGSBRf
- https://dashboard.balena-cloud.com/devices/f00da3b83b8bc879fed1927c1bfecde8/summary

# RPi indoor
- faithful-oily-wren
- https://testnet-explorer.helium.com/hotspots/1Zx68c1ghuwd7UCWqvCKTgFxR1ZvfBLSk4suQnmFRHVw4o4yKev
- https://dashboard.balena-cloud.com/devices/6e54f41d04eec1886cd89eea6ca61f08/summary

# RPi outdoor
- thankful wintergreen wren
- https://testnet-explorer.helium.com/hotspots/1YwZHCKQhdZ3HgjmHuxVAwmuVedX9BqxLq4KzeWTJ638JqpYCiF
- https://dashboard.balena-cloud.com/devices/fd5f350f18f50c45a1a23eeb1a3170da/summary


It's not 100% clear [from Discord](https://discord.com/channels/404106811252408320/806247651950460988/958123480640024596) what the state of helium/miner will be at the time they go live with light miners and how that will compare to helium/gateway-rs. In my opinion, we should continue to prioritize gateway-rs integration as that is the inevitable future. At the same time, I'll keep an eye on how things perform using their maker instructions on Helium testnet. @vpetersson @shawaj

**Comment by marvinmarnold** [comment]
@shawaj @vpetersson fyi not currently witnessing anything. Haven't been able to look into why yet.

**Comment by shawaj** [comment]
> @shawaj @vpetersson fyi not currently witnessing anything. Haven't been able to look into why yet.

@marvinmarnold do you mean the 3 hotspots above are all on testnet but not witnessing each other? maybe speak to helium on discord

**Comment by shawaj** [comment]
and should we not leave this open if not witnessing?

**Comment by marvinmarnold** [comment]
@shawaj I let them know on Discord and waiting for a response. The intention is for @MuratUrsavas to take this over and track the work as part of: https://github.com/NebraLtd/hnt-products/issues/7

**Comment by pritamghanghas** [comment]
**These two rockpi miners are also on testnet:**
Balena:
https://dashboard.balena-cloud.com/devices/ec30aba9527d5dcd3dda93ecfca85c48
https://dashboard.balena-cloud.com/devices/faa7d571d415cc3a79d4c471ca714f33

Testnet explorer:
https://testnet-explorer.helium.com/hotspots/hex/883d146b3dfffff
https://testnet-explorer.helium.com/hotspots/hex/883d146b31fffff
