### ISSUE TITLE
Ensure scheduled version update is working correctly.

### ISSUE THREAD

**Issue by pritamghanghas** [NebraLtd/helium-miner-software#412]
As a developer I want to make sure that auto bump for gateway-rs is working correclty 

**Acceptance Criterion**
As a result of this workflow, PR should happen for following files:
- [ settings.ini ](https://github.com/NebraLtd/helium-miner-software/blob/master/settings.ini) is updated correctly 
- hm-gatewayrs [dockerfile](https://github.com/NebraLtd/hm-gatewayrs/blob/main/Dockerfile)

> Basically I think you will need to do another PR with new workflows to the master branch or the auto-updates won't work

_Originally posted by @shawaj in https://github.com/NebraLtd/helium-miner-software/issues/409#issuecomment-1081920038_

**Comment by shawaj** [comment]
Possibly closed by #708

**Comment by shawaj** [comment]
Working fine
