### ISSUE TITLE
The rock pi miner is not responding 

### ISSUE THREAD

**Issue by yaswanth-source** [NebraLtd/helium-miner-software#429]
Hi I have 2 new rock pi miners and one of them is not responding  from the beginning  , the green didn't  turned  on
  The other one is connected  in starting  but after  a day the same problem 
    I tried  to connect  them through  ethernet  cable , but in my WiFi web page , and these  devices  are not even  connected  to Internet  , 
Can you please  react as fast as you can , 
![Screenshot_20220424-155508_Chrome.jpg](https://user-images.githubusercontent.com/85169964/165023979-8de8219a-73fc-496f-b07d-23a279961f62.jpg)
![Screenshot_20220425-103505_Chrome.jpg](https://user-images.githubusercontent.com/85169964/165024059-063794c4-e933-40d1-a079-a7ae753fc884.jpg)
Can you have look at my miners  and let me know .

**Comment by vpetersson** [comment]
This is not a support forum. Please contact customer support.
