### ISSUE TITLE
Hardware documentation

### ISSUE THREAD

**Issue by Bra1nsen** [NebraLtd/helium-miner-software#439]
Sorry for posting here. Nebra isnt answering :(

I would like to add a small 5V fan. I cant find specs to the boards/pins. Any Information out there?

**Comment by shawaj** [comment]
This is not a support channel.

Please email support@nebra.com

**Comment by Bra1nsen** [comment]
Nebra isnt answering since 2 weeks

**Comment by shawaj** [comment]
Adding a fan is not supported
