### ISSUE TITLE
Add Cotx X3 hotspot support

### ISSUE THREAD

**Issue by MuratUrsavas** [NebraLtd/helium-miner-software#465]
As the necessary parameters has been already added to `hm-pyhelper` we now need to add it to the base repository and make necessary arrangements.

**Acceptance Criteria**

- [x] Add variant into variant_definitions in hm-pyhelper repository
- [x] Create custom inputs (e.g. additional buttons) and outputs (e.g. additional LED's) in the new variant and update the logic in other repositories if necessary.
- [x] Release and publish it via CI/CD pipeline
- [x] Bump hm-pyhelper for hm-pktfwd, hm-diag and hm-config repositories and push them to create necessary docker images (could take a while) (Example pull request for hm-config in such case)
- [x] Create related production Balena fleets (will be called just fleets from now on) as "helium-<device_type>-[variant]-[frequency]-[user]" (parameters in brackets are optional)
- [x] Edit configuration parameters of the fleet
- [x] Add VARIANT and FREQ environment variables into fleet variables
- [x] Update automation steps in this repository for newly created fleets
- [x] Add sentry environment variables into fleet variables
- [x] Modify generate-images.sh from NebraLtd/hotspot-production-images repo root.
- [x] Modify generate-urls.sh from NebraLtd/hotspot-production-images repo root.
- [x] Modify generate-images.yml from NebraLtd/hotspot-production-images repo under .github/workflows folder.
- [x] Modify settings.ini file if necessary

**Comment by MuratUrsavas** [comment]
@vpetersson @marvinmarnold Could you create a test fleet for Cotx?

**Comment by marvinmarnold** [comment]
> @vpetersson @marvinmarnold Could you create a test fleet for Cotx? And also `helium-cotx`

Done

**Comment by MuratUrsavas** [comment]
Testnet is looking good. Merging to `production`.
