### ISSUE TITLE
Why is Redis on staging more expensive than production

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#492]
## Staging
![image.png](https://images.zenhubusercontent.com/6111782bbed147dc514083ae/30d75ba4-4d38-45af-bf64-07159dd5dd9d)

## Production
![image.png](https://images.zenhubusercontent.com/6111782bbed147dc514083ae/018479df-5ae6-4635-a88a-4aed08f05116)

**Comment by htsili** [comment]
@marvinmarnold 
Production
<img width="491" alt="Screenshot 2022-07-15 at 17 07 47" src="https://user-images.githubusercontent.com/21157614/179263576-9890b86b-9534-4b27-9fd9-848e0ae84f01.png">
<img width="491" alt="Screenshot 2022-07-15 at 17 08 01" src="https://user-images.githubusercontent.com/21157614/179263582-090da17e-1326-4978-aa14-b8a1b4bece11.png">
Staging
<img width="491" alt="Screenshot 2022-07-15 at 17 08 27" src="https://user-images.githubusercontent.com/21157614/179263586-78e020df-df2b-4d3e-9608-a51ea6b62010.png">

The staging instance is a bigger size.

**Comment by marvinmarnold** [comment]
Why is it bigger?

**Comment by htsili** [comment]
@marvinmarnold no idea I didn't set it up.

**Comment by marvinmarnold** [comment]
@NebraLtd/cloud-team any reason we can't scale it down?

**Comment by marvinmarnold** [comment]
@htsili can you scale this down to the same as production?
