### ISSUE TITLE
Nebra register hotspot

### ISSUE THREAD

**Issue by kevthejedi** [NebraLtd/helium-miner-software#51]
When setting up the Nebra hotspot I am getting the attached message at the final stage to register hotspot. I have tried closing app. Turn off and turn on Bluetooth and repeating and get the same error message at final stage. Tried for 2 days now at different locations and using WiFi and Ethernet same error message . The antenna screw was very loose on receipt of Nebra which I have since tightened with snipe pliers. 
![4DD94C17-285C-48A9-9F40-42B3C1B0D0C7](https://user-images.githubusercontent.com/84894870/119774099-90a6a680-beb9-11eb-9ca3-e6699c85e4f1.png)

**Comment by ryanteck** [comment]
@kevthejedi For this issue we would require some details to be sent via email to resolve this for you.

Could you send the following information to sales@nebra.com

- Model of unit :
- Mac address of the unit (Shown as ETH on sticker):
- Frequency of the unit (Shown as Freq on sticker):
- How are you connecting it to internet? (Ethernet, Wi-Fi, Cellular):
- How are you powering the unit? (Included adaptor, POE, Third party adaptor):
- If the issue relates to initial setup of the hotspot:
- What make &  model of phone are you using?
- What version of the Helium App are you using?
- Do you have any screenshots of any error codes?

**Comment by ryanteck** [comment]
Actually @kevthejedi I've just found your ticket already and will respond via there.
