### ISSUE TITLE
Move miner diagnostics from gateway-config to diagnostics container

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/helium-miner-software#55]
Move the miner diagnostics processing code to the diagnostics container, that way we can show the same data  on the diagnostics page and then in the config speed it up by presenting the cached copy.

**Comment by shawaj** [comment]
Is this still relevent @vpetersson @marvinmarnold ?

**Comment by vpetersson** [comment]
We can close this out. This will be solved with time with the introduction of hm-pyhelper. We are slowly starting to adopt it in places.
