### ISSUE TITLE
Pass helium name back to balenacloud

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#58]
Not sure how easy this would be, but for support purposes it would be useful to be able to pass the helium name of a miner (and possibly its blockchain address) back to balenacloud as a tag or something similar.

I believe this is possible using:
https://github.com/balena-io-examples/device-tags

**Comment by shawaj** [comment]
guess this will be fixed by https://github.com/NebraLtd/hm-diag/pull/156

**Comment by vpetersson** [comment]
Yep. That's the first iteration but will solve this.

Maybe we just rename the device name in Balena to the Animal Name. The Balena name doesn't really add much value.

**Comment by vpetersson** [comment]
https://github.com/NebraLtd/hm-dashboard/issues/554
