### ISSUE TITLE
Balenahub page empty

### ISSUE THREAD

**Issue by ifeign** [NebraLtd/helium-miner-software#608]
None of the links to your fleets work anymore, has this project been discontinued?
<img width="1677" alt="Screenshot 2023-02-02 at 1 53 02 PM" src="https://user-images.githubusercontent.com/32289760/216436010-a397aee4-c047-440a-9703-89e3f0440f63.png">

**Comment by shawaj** [comment]
No it's a technical issue. Be back shortly

**Comment by ifeign** [comment]
> No it's a technical issue. Be back shortly

Good to know, thanks

**Comment by uros76** [comment]
Hi. Any update? 😢

**Comment by shawaj** [comment]
Nothing yet I'm afraid.

But you can download the software directly from github.

What miner is it for?

**Comment by uros76** [comment]
MNTD / RAK and Controllino.

**Comment by shawaj** [comment]
> MNTD / RAK and Controllino.

RAK - https://github.com/NebraLtd/helium-rak/releases
Controllino - https://github.com/NebraLtd/helium-controllino/releases

The zip files are the image and the sha512 is the checksum.

**Comment by uros76** [comment]
> > MNTD / RAK and Controllino.
> 
> RAK - https://github.com/NebraLtd/helium-rak/releases Controllino - https://github.com/NebraLtd/helium-controllino/releases
> 
> The zip files are the image and the sha512 is the checksum.

Thank you 👍. 

As for updating private forked fleets on balena this is still work in progress?

**Comment by shawaj** [comment]
You can already do that. You can just use the following link format:

Rak - https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/NebraLtd/helium-rak

Controllino - https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/NebraLtd/helium-controllino

**Comment by ifeign** [comment]
> You can already do that. You can just use the following link format:
> 
> 
> 
> Rak - https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/NebraLtd/helium-rak
> 
> 
> 
> Controllino - https://dashboard.balena-cloud.com/deploy?repoUrl=https://github.com/NebraLtd/helium-controllino 

Oh cool, never seen those URLs, I've been cloning the repo then pushing it with the Balena CLI

**Comment by shawaj** [comment]
Yeah it's quite handy, you can just deploy the update to your fleet by going to link and selecting to deploy to an existing fleet.

You can also still clone the github repo and push to your fleet using BalenaCLI

Also, fairly soon we will have instructions on the github pages about how to fork the GitHub repo, and GitHub actions that you can set up to make the updates to your fleet automatically each time we push an update.

Should make things very easy and flexible for all requirements

**Comment by ifeign** [comment]
That’s awesome! I think I have the actions mostly figured out, but
instructions would be great

**Comment by shawaj** [comment]
Closing this as the apps are now all available at:
https://hub.balena.io/apps/ and https://hub.balena.io/apps/

You can just search for "helium" and you will find them all
