### ISSUE TITLE
2 hotspots updated result in 'Miner Is Still Loading' error

### ISSUE THREAD

**Issue by whittinghamj** [NebraLtd/helium-miner-software#67]
I had 2 Nebra indoor hotspots updated and ready to ship to hosts locations tomorrow.

there was a software update so I decided to plug them in here and let them update but both now result in the following error on the diag page.

'Miner Is Still Loading' 

Any ideas please?

**Comment by shawaj** [comment]
This is an issue at Helium end in the miner it seems...
https://github.com/helium/miner/issues/816

**Comment by shawaj** [comment]
@whittinghamj have these units updated to the 12.0 update? Is the issue still there?

**Comment by ryanteck** [comment]
@shawaj  I'm only just pushing that to Prod now.

@whittinghamj could you report back in about an hour as to if this has fixed it?

**Comment by shawaj** [comment]
@whittinghamj how is this looking on your side?

**Comment by shawaj** [comment]
@whittinghamj just to check - has this issue now been resolved for you?

**Comment by shawaj** [comment]
Closing as no response

**Comment by suprnrdy** [comment]
I'm seeing more of these pop up. Can this be due to failed software updates (either from poor internet connections or disconnecting mid update?)

**Comment by dowjames** [comment]
Having the same issue.
