### ISSUE TITLE
2023.02.07.0-26-helium-rak-2023-03-28-OpenFleet broken, miner doesn't witness or beacon

### ISSUE THREAD

**Issue by ifeign** [NebraLtd/helium-miner-software#703]
**Describe the bug**
The latest build doesn't work, even though the radio shows as active, it does not beacon or witness

**To Reproduce**
Update to the latest build

**Comment by shawaj** [comment]
are you running on balenaCloud or our openfleet release?

**Comment by shawaj** [comment]
Do you get any error messages in the backend?

TBH I have RAK one on our testnet which looks fine.

Have you tried rebooting?

**Comment by ifeign** [comment]
It seems a simple reboot fixed everything.
