### ISSUE TITLE
Unable to clear WiFi credentials

### ISSUE THREAD

**Issue by edpgcooper** [NebraLtd/helium-miner-software#71]
Initial setup was with WiFi, switched to an Ethernet connection, seem unable to clear WiFi credentials - no amount of "forget this network" using the the App actually stops it connecting via WiFi, device always gets two IP addresses - and its unclear if it always prioritises Ethernet.

**Comment by shawaj** [comment]
I think this might be an issue with the hotspot app.

Are you getting the issue where you click "forget" and it asks you to enter your WiFi password again?

**Comment by edpgcooper** [comment]
Last time I tried (5 weeks ago) I was still struggling with it, seemed like if the Ethernet briefly dropped it would just revert to Wi-Fi no matter how poor Wi-Fi was.  In the end I MAC banned the Wi-Fi as I couldn’t get it to stop connecting to it.  This resolved all my problems.
________________________________

**Comment by edpgcooper** [comment]
> @edpgcooper did you follow the "forget wifi" option in the app?

Yes, I tried this several times about 6 weeks ago now, in that location I've MAC banned the miner as I could not stop it connecting to the WiFi any other way.  Since this is working, and it's a remote location, I'm unlikely to try it again any time soon.

**Comment by elapstor** [comment]
@shawaj Yes, I ve done that multiple times. The weird thing is, its still connecting to the WiFI. Though the helium says Ethernet and it is connected to Ethernet however it's also connected to the WiFi as well and assigned two different IPs. The only way to stop it was to manually ban its Wlan mac address. Then it appears to work but its in a stuck state and its not processing any blocks (diagnostic page updating but block height remains stationary) (location unasserted).

**Comment by millerz1897** [comment]
@edpgcooper

> Initial setup was with WiFi, switched to an Ethernet connection, seem unable to clear WiFi credentials - no amount of "forget this network" using the the App actually stops it connecting via WiFi, device always gets two IP addresses - and its unclear if it always prioritises Ethernet.

I have the same issue.  I can tell you plainly that (at least on my outdoor Nebra (2021.09.27.0) does not prioritize ethernet.  The helium app says it is connected to eth but it doesn't use it when I look at traffic.

After a dozen attempts of rebooting, waiting a minute, then longer, then longer, I was able to CHANGE the wifi network but not disable it completely.  I even tried removing the USB Wifi NIC to get it to use ethernet.  No luck.

I see bits of traffic getting to the blockchain and have the appropriate port-forwarding (port in place outbound all, and inbound 44158)   to my internal id.  But all I see it the blockchain rising but no sync happening.  I also see myself on the neebra dashboard app and helium blockchain.  So something is working.

Also, @shawaj no amount of reboots are getting the software to update on my device.  00:BD:27:00:1A:B4 is there a way to administratively push this?  Or rebuild part of the device to start fresh? Hoping an update would fix my issues...

**Comment by shawaj** [comment]
Closed in favour of https://github.com/NebraLtd/hm-config/issues/131
