### ISSUE TITLE
Wi-Fi adaptor FF:FF:FF:FF:FF:FF issue

### ISSUE THREAD

**Issue by ryanteck** [NebraLtd/helium-miner-software#72]
On some units the Wi-FI adaptor is going into a state where it disables itself, 

Needs investigation.

**Comment by ryanteck** [comment]
Testing out disabling power_mgnt on one unit with command ```modprobe r8188eu rtw_power_mgnt=0```

It may be that we need to request Balena to add this to the nebhnt device.

**Comment by ryanteck** [comment]
And first remove the old driver with `rmmod r8188eu`

**Comment by ryanteck** [comment]
Unfortunately it looks like the above fix may have not worked.

I have two of the suspect adaptors on their way to me.

**Comment by shawaj** [comment]
@ryanteck from the unit? Or from customers? Do we need to send them replacements?

**Comment by ryanteck** [comment]
From one customer directly (ap).

Looks like a faulty batch of adaptors.

**Comment by shawaj** [comment]
Seems unlikely to me as they work some of the time.

Feels more like a driver issue than a hardware issue

**Comment by ryanteck** [comment]
I'm not certain on either yet.

Some customers have the same chipset without any issues at all.

In this case the customer had 10 hotspots from the same batch, 2 with the
adaptor issue.

The issue I believe when they switched them between units followed the
adaptor.

If it was driver I would expect it to be more widespread (e.g all 10
failing). But I'm not ruling it out as drivers either yet.

**Comment by pooley92** [comment]
Hi Guys, 

To provide some clarity. 
5 of the v1 Nebra old style with the white writing were all good. 
I then received 5 of the new style v2 cases. 3 of them were good and 2 of them exhibit this wifi MAC error. 
Moving the wifi adapter to a good working HS moved the issue to that HS. I kept one as a control.

Sent the two adapters to Ryan to see if the issue can be replicated on his side.

**Comment by ryanteck** [comment]
The faulty adaptors from @pooley92 arrived today, so far been able to repliacte with one. Now testing with the second and then re-testing with the one that was in my unit.

**Comment by KevinWassermann94** [comment]
Can we handle this with priority? This issues affects a lot of customers

**Comment by shawaj** [comment]
@KevinWassermann94 still haven't got to the bottom of this. Think it's a driver level issue but not been able to work it out yet

**Comment by shawaj** [comment]
@vpetersson do you know if we solved this issue?

**Comment by vpetersson** [comment]
I've still seen this on some outdoor units in the last few months. It's likely a driver issue (or possibly, power saving), but haven't dug into it. Also, not sure how much of a priority it is now with the ROCK Pi based version.
