### ISSUE TITLE
Update to GA 2021.06.21.0

### ISSUE THREAD

**Issue by bigdaveakers** [NebraLtd/helium-miner-software#74]
Is it planned to include this optional update?

**Comment by ryanteck** [comment]
It's gone into testing this morning with this commit https://github.com/NebraLtd/helium-miner-software/commit/1da77089bbdb35c0d8afb44690dc094a2c4dfac9

It'll likely get pushed out this evening widespread.

**Comment by bigdaveakers** [comment]
Has it gone yet?

**Comment by shawaj** [comment]
It would be here if it had https://github.com/NebraLtd/helium-miner-software/pulls?q=is%3Apr+is%3Aclosed

So doesn't look like it

**Comment by ryanteck** [comment]
Yeah sorry got delayed, I need to revert one of the other containers back before merging to production.

Will do this now.

**Comment by ryanteck** [comment]
PR at 

https://github.com/NebraLtd/helium-miner-software/pull/75

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/helium-miner-software/pull/75
