### ISSUE TITLE
HS stuck in the migration process

### ISSUE THREAD

**Issue by jbb-kryo** [NebraLtd/helium-miner-software#768]
- [x] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
My HS was onboarded with blue app unfortunately in the period of Solana migration, I think that blockchain snapshot didn't included HS as it should. Now, because of this in new helium app I can't see anything, including earnings and other stats. Can someone fix this issue related to my HS.

**Comment by shawaj** [comment]
What miner do you have and what's the animal name?

**Comment by shawaj** [comment]
Also, it sounds like you may not have migrated your wallet properly.

In the black Helium app you need to go to settings, and then click migrate wallet

Also, are you sure you restored the wallet from the old blue helium app too the new black Helium app correctly?

**Comment by jbb-kryo** [comment]
> What miner do you have and what's the animal name?

acidic-strawberry-mule

**Comment by jbb-kryo** [comment]
> 

Attempted both things, including resurrecting from the original seed phrase. According to the app, migration is fine.

**Comment by jbb-kryo** [comment]
> Also, it sounds like you may not have migrated your wallet properly.
> 
> In the black Helium app you need to go to settings, and then click migrate wallet
> 
> Also, are you sure you restored the wallet from the old blue helium app too the new black Helium app correctly?

Migration shows as fine, however the wallets I have and the seed phrase resurrects do not match what is shown for the miner in Hotspotty, which is also incorrect as the miner is inactive.

**Comment by shawaj** [comment]
The address for the owner of that hotspot is...

14FkiprdidAQsjpbGyJLBrC6vNAgYRgxKD313sYaqU834pFdz3G

Solana address...
CciPmboL2D9c6T1eQAVdntvAtRZCnsdQfhb2xb4bsSWu

Which says it does not exist.

This means that your wallet hasn't migrated https://explorer.solana.com/address/CciPmboL2D9c6T1eQAVdntvAtRZCnsdQfhb2xb4bsSWu

**Comment by shawaj** [comment]
@jbb-kryo 

> In the black Helium app you need to go to settings, and then click migrate wallet

**Comment by shawaj** [comment]
Last but not least... On hotspotty it shows you are earning rewards so the hotspot is definitely working fine. You just need to properly migrate the wallet

**Comment by shawaj** [comment]
I've also just seeded/inflated your wallet using the widget here...
https://docs.helium.com/solana/migration/wallet-user/

So it now will show as existing.

But you still need to do the migration thing in the black Helium wallet app as mentioned.

Closing as this will fix the issue

**Comment by shawaj** [comment]
Last but not least, with the new IoT token you have to go to the collectibles area (diamond logo at bottom of the app) and claim the tokens for them to go into your wallet :-)

**Comment by jbb-kryo** [comment]
That wallet showing is really old and not the current wallet. It was switched out way before migration, hence me being even more confused now. That is the problem. I'm now going through my archives for that old wallet. Is my hardware bricked if I can't find that?

**Comment by jbb-kryo** [comment]
> I've also just seeded/inflated your wallet using the widget here... https://docs.helium.com/solana/migration/wallet-user/
> 
> So it now will show as existing.
> 
> But you still need to do the migration thing in the black Helium wallet app as mentioned.
> 
> Closing as this will fix the issue

Closing before the person who's raised it has confirmed a fix is really not great. And it leads to this - having to reopen it as it blatantly isn't resolved yet.

**Comment by shawaj** [comment]
If you lost access to the wallet that owns the device there's nothing that can be done other than re-keying the miner (which costs $25 for labour and $50 for reonboarding it)

Bear in mind that previously (before solana migration) you could only transfer a hotspot if it had recent activity. If it didn't the transfer would have failed. In any case it definitely hadn't been transferred before the solana transition... So the only ways are as mentioned above.

In any case, this isn't Nebra support. You even ticked a box saying that this was a bug report and not a support request.

Since this isn't a bug report and isn't related to software development side of things I'll leave this issue closed. If you can't get access to your wallet and you need the miner re-keying you will need to create a support ticket in the link in your first post here.

**Comment by jbb-kryo** [comment]
> If you lost access to the wallet that owns the device there's nothing that can be done other than re-keying the miner (which costs $25 for labour and $50 for reonboarding it)
> 
> Bear in mind that previously (before solana migration) you could only transfer a hotspot if it had recent activity. If it didn't the transfer would have failed. In any case it definitely hadn't been transferred before the solana transition... So the only ways are as mentioned above.
> 
> In any case, this isn't Nebra support. You even ticked a box saying that this was a bug report and not a support request.
> 
> Since this isn't a bug report and isn't related to software development side of things I'll leave this issue closed. If you can't get access to your wallet and you need the miner re-keying you will need to create a support ticket in the link in your first post here.

----> Ticket now answered. Thanks.
