### ISSUE TITLE
Document how disk images are built

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/helium-miner-software#77]
Perhaps the wrong repo, but I have not come across any documentation on how the disk image for the miner is built. Please document this somewhere.

**Comment by ryanteck** [comment]
It's located here

https://github.com/NebraLtd/hotspot-production-images

**Comment by ganey** [comment]
Is that a private repo? 404 here

**Comment by ryanteck** [comment]
Yes it is a private repo currently.

**Comment by shawaj** [comment]
Closed in https://github.com/NebraLtd/hotspot-production-images
