### ISSUE TITLE
Automate miner bump process

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#84]
The miner bumping process is a very simple, but currently manual process when Helium tag a new GA at https://quay.io/repository/team-helium/miner?tab=tags

Ideally we should automatically bump this, and pull into our testnet, perform some automated tests and automatically issue a PR to production for review and manual confirmation.

Relates to https://github.com/NebraLtd/hm-miner/issues/4

**Comment by shawaj** [comment]
Wonder whether we can have it auto update with a PR here when hm-miner tags a new release?

**Comment by vpetersson** [comment]
Yes, should be possible. There are some Actions/Bots that span repos.

**Comment by shawaj** [comment]
This is now completed using Mr Bump
