### ISSUE TITLE
Nebra Rock pi Indoor - beacon/witness pattern: can witness fine until a beacon is sent

### ISSUE THREAD

**Issue by hawamahal1** [NebraLtd/helium-miner-software#861]
The issue I am having is similar to this issue posted in 2021, I am located in Australia if that makes any difference. Since Australia had a few frequency changes in the last about 9 months. AU915 to AS923 and back to AU915.

#https://github.com/helium/miner/issues/1133

I just recently onboarded in new Nebra Rock pi indoor version. The original firmware was 2022.08.17.1 (4492c46) and asserted location.. Even after 24 hours of leaving it connected to the internet (ethernet), the dashborad still said " Awaiting Location Assertion"

I updated the firmware to the latest version from hub.nebra.com and now on the dashboard all looks OK, but the hotspot stops witnessing as soon as it beacons. The sequence is as follows

hotspot witnesses other beacons
hotspot sends own beacons
hotspot own beacon returns 0
hotspot stops witnessing
If i restart the hotspot the same sequence repeats. If I leave it ON and connected, it tries to beacon every 6 hours, but gets no witnessing. Also I have checked heliumgeek and moken explorer, the hotspot does not witness anything selected or unselected or invalid.

Another interesting thing is that when I flash the hotspot with an old firmware ( 1.0.2-2), it works fine for some time ( maybe an hour or so) and it eventually updates to the latest firmware and it stops witnessing.

I raised a support ticket as well 430636. Don't know if this is a support issue or a software bug.

**Comment by shawaj** [comment]
Please don't open multiple issues and support tickets. It just makes it more difficult to reply

**Comment by hawamahal1** [comment]
OK. I will wait for the reply on the original ticket. Thanks

**Comment by shawaj** [comment]
Hotspot looks fine to me and is still witnessing https://heliumtracker.io/hotspots/1026512
