### ISSUE TITLE
Cannot flash to SD Card

### ISSUE THREAD

**Issue by skki3330** [NebraLtd/helium-miner-software#880]
- [ ] I understand that this is only to report software bugs and **not** for customer support. Please use [nebra.io/helium-support](https://nebra.io/helium-support).

**Describe the bug**
I have now tried flashing this software to 3 different sd cards using 4 different readers using 2 different computers and even 3 different flashing software programs and everytime it just fails
**To Reproduce**
1. Go to '...' ive been using your steps on this page https://support.nebra.com/support/solutions/articles/24000078653-getting-started-with-pisces

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shawaj** [comment]
This is not an issue with our firmware.

You need to use Etcher or Rufus or win32diskimager or a similar tool.

**Comment by shawaj** [comment]
Just FYI...if you are using Etcher on Windows, it often says it has failed when it has actually programmed correctly.

**Comment by skki3330** [comment]
Hi Aaron,
I've tried rufus aswell that fails also I will try the other o e you said.
I'm currently downloading an older version of your software to see if that
will work.
I've been at this for 12 hours now
Craig
