### ISSUE TITLE
Nebra software version / semantic versioning or similar?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/helium-miner-software#97]
Might be useful to have a semantic versioning / automatic changelog or something at some point. Not super urgent, but could be useful IMO

**Comment by vpetersson** [comment]
Definitely possible but I'd say that has to wait until we have a bit more stable releases as that adds a fair bit of overhead.

**Comment by shawaj** [comment]
Ah ok makes sense. Main reason I thought about it was because a few people have asked for a feed / changelog to get updates about be releases and when they are pushed from our side

**Comment by KevinWassermann94** [comment]
I have suggested adding a changelog to the dashboard here: https://github.com/NebraLtd/dashboard-issues/issues/25

**Comment by vpetersson** [comment]
Closed in favor of https://github.com/NebraLtd/hm-miner/issues/47
